### ISSUE TITLE
Connection tab colors

### ISSUE THREAD

**Issue by Maikel-Koek** [Sequel-Ace/Sequel-Ace#1013]
Since the last update, tabs are not completely colored anymore, now connection tabs only have a small dot on the right side containing the color I configured.

I think this is a huge step back, and really confusing when I have multiple tabs open, especially when dealing with production environments.

Is there maybe a setting somewhere I missed, to configure (revert) this?
Thanks!

**Comment by Kaspik** [comment]
There is not. We removed custom tab bar completely and implemented NSWindow native tabbing giving us a lot more stability, features etc. Native tabs have NSAccessoryView we can customize, but using full tab to colorize it would mean no title for tab, or a lot of work around that. We've explored couple of options (like bottom line below title, top line above title, square on right side, circle on right side) and ended up with current solution as also the most elegant one kind of similar to tags in Finder etc.

What exactly is confusing about that except it's new and people are not used to that and are used to check the whole tab? If we find usability issues we will be happy to spend more time on this but personally I think there are more important things and this is just about getting used to it again.

Totally open to other design ideas as well!

**Comment by ChristianVermeulen** [comment]
I agree with @Maikel-Koek. This way of colouring is not clear at all. I often switch between local (green) and production (red) tabs and need a clear indication of which environment I am working in.

The point is not so much that it is confusing, but that it is no longer clear in which environment you are working. Finding this DOT on your total screen real estate is a much bigger strain on the eyes than having a clear coloured tab in your peripheral vision.

I'm not sure what the problem was with the original tab system, personally I experienced no issues with it, so I highly doubt this trade off was worth the effort unfortunately :(.

**Comment by Kaspik** [comment]
The tradeoff was one of the biggest things this app ever achieved infrastructure-related. That fixed many open issues, many connection issues, and our issue count decreased from almost a hundred to current state - and opened completely new ways to improve the app and possibly bring new feature sooner rather than later. :)

There will always be people that liked that, and people that like this (even discussion on the final PR mentioned like vs. don't like - https://github.com/Sequel-Ace/Sequel-Ace/pull/970).

I get your point about the visibility, happy to review design proposals, but the previous solution is not possible anymore.

**Comment by PascalBrouwers** [comment]
I agree, way of colouring is not clear at all with this new design:
https://user-images.githubusercontent.com/7204168/111072092-5f812180-84d9-11eb-8e45-9d81fd662ca6.png
Maybe change the font color of the tab so make it more clear? I don't know what the possibilities are.

**Comment by ChristianVermeulen** [comment]
@Kaspik hmm I hardly call 3 comments and directly merging after your own reply a "discussion" 🤔.. And I don't agree with @samualbradshaw either. @Jason-Morcos raised a very valid point which in my opinion needs more research before being dismissed like that. This is a very big UX change and has grave impact on daily users.

I'm not too familiar with this new native component so I don't exactly now the possibilities which makes it pretty hard to come up with a viable solution in this new setting. I'm hoping someone else has a better idea of this and can see a better way to have a clearer indication in these native tabs.

Perhaps [BackgroundView](https://developer.apple.com/documentation/uikit/uitableviewcell/1623260-backgroundview) can be of some help here?

> UITableViewCell adds the background view as a subview behind all other views and uses its current frame location.

**Comment by Maikel-Koek** [comment]
Double-clicking to duplicate a tab doesn't work anymore either, I guess this also has to do with this tab implementation?

**Comment by Kaspik** [comment]
Yes, that's not system behavior (or at least I'm not aware any system app would do that), so CMD+SHIFT+T is your friend here.

Couple of quick things that I just tried. Might be better than current circle (prefer the top line), but as I liked the previous solution, I'm not the one to compare. :)

<img width="1828" alt="Screenshot 2021-04-07 at 16 00 48" src="https://user-images.githubusercontent.com/7204168/113879169-8b32b700-97ba-11eb-960a-35bc5e3e3923.png">
<img width="1828" alt="Screenshot 2021-04-07 at 16 00 19" src="https://user-images.githubusercontent.com/7204168/113879152-87069980-97ba-11eb-967f-10119b4b789b.png">

**Comment by Maikel-Koek** [comment]
@Kaspik Cmnd+shift+T seems to work (well, when the app doesn't crash completely, that is, but that also happened half the time when double clicking was still working), so that's a solution for me.

As for the colors: Way better! I actually think I prefer the bottom line, but that's a matter of opinion I guess.

**Comment by ChristianVermeulen** [comment]
@Kaspik This is much better already! Personally I prefer the bottom line, but both are a major improvement anyway so I can live with the top line if that has the most votes :).

Thanks for taking this serious and instantly working in it!

**Comment by samuelbradshaw** [comment]
I think part of the reason it might be easy to miss which database you're editing is because of the long title that shows as the tab title, and is repeated for each tab. In particular, I'm wondering if it would be a good idea to get rid of the MySQL version from the title of the tab.

**Comment by ChristianVermeulen** [comment]
@samuelbradshaw

> I'm wondering if it would be a good idea to get rid of the MySQL version from the title of the tab.

Personally I use this a lot, we have servers on 5.7 and some already on 8.0. So I would be pretty sad to see the version go :).

That being said, We could probably make due with just the host + db name. The whole path to the active table might be a bit overkill?

**Comment by samuelbradshaw** [comment]
> @samuelbradshaw
> 
> > I'm wondering if it would be a good idea to get rid of the MySQL version from the title of the tab.
> 
> Personally I use this a lot, we have servers on 5.7 and some already on 8.0. So I would be pretty sad to see the version go :).
> 
> That being said, We could probably make due with just the host + db name. The whole path to the active table might be a bit overkill?

For your use case, do you need to see the MySQL version on the tab title – i.e. while you're on one tab, you can see the MySQL version for all of the other tabs – or would putting it somewhere else, like the status bar, meet your need?

**Comment by ChristianVermeulen** [comment]
> or would putting it somewhere else, like the status bar, meet your need?

At first I thought the window title, but then I realised this is probably the same thing as the tab title. The status bar would be sufficient as well yes!

**Comment by Maikel-Koek** [comment]
I actually like being able to see my active table in the window title, I'd like to know which MySQL version I'm on but that's not always that relevant, so moving that to the status bar would be great! Or in the little 'Information' box underneath my table list or something.

**Comment by Kaspik** [comment]
Let's please open separate issue from coloring one if you think there is some. :)

**Comment by djkgamc** [comment]
One thing I think everyone might be missing is that if you have one tab per window, you won't see the coloring at all anymore (and so you can't differentiate between windows), which is why this is a sort of "breaking change".  

One hacky solution is to force myself to open two tabs per window no matter what, which is obviously dumb.  Does this new line solution show up if there is only one tab?
