### ISSUE TITLE
Open SSH/socket connection via mysql://

### ISSUE THREAD

**Issue by brandondove** [Sequel-Ace/Sequel-Ace#108]
- What version of Sequel-Ace are you using? - Sequel Ace 2.0.2, Build 2033
- What version of macOS are you running on? - MacOS Catalina, 10.15.5
- What device(s) are you using Sequel-Ace on? - MacBook Pro 16"

I noticed that Sequel Ace will open a connection via URL (mysql://user:pass@host:post/dbname) just like Sequel Pro did. Is there a way to open a socket connection via URL?

Context - I'm writing an add-on for Local by Flywheel to open connections in Sequel Ace because they currently only support Sequel Pro. Local uses sockets for connections so if there's a way to open Sequel ace with this type of connection that would be awesome.

**Comment by Jason-Morcos** [comment]
Is there a url standard for mysql:// URLs for sockets? Probably not hard to implement, but would like to follow a convention if one exists!

**Comment by brandondove** [comment]
This is the only source I've really found about a standardized URL structure for MySQL database connections. - https://dev.mysql.com/doc/refman/8.0/en/connecting-using-uri-or-key-value-pairs.html

I'm not that familiar with doing this but it looks like Sequel Ace already supports the MySQL protocol. I'm just not sure how adding the socket to that URL would work.

**Comment by jamesstout** [comment]
I managed to change the registered app for the `mysql` URL scheme to a sequel ace instance attached to my debugger. When I ran:

`open root@localhost?socket=%2Ftmp%2Fmysql.sock`

It get's picked up by `handleMySQLConnectWithURL`, but doesn't process the socket part, seems to just expect TCP/IP connections. 
![Screenshot 2020-06-26 at 4 15 01 PM](https://user-images.githubusercontent.com/1576190/85838046-87095000-b7cb-11ea-9d5a-421c59be75bc.png)

**Comment by Jason-Morcos** [comment]
Looks like we'd just have to parse the queryString then and throw the value into the `"socket"` key- not too bad?

**Comment by jamesstout** [comment]
almost got it working: https://github.com/jamesstout/Sequel-Ace/tree/url-scheme

**Comment by Jason-Morcos** [comment]
The one big complication to this whole thing could be #113 though - that may confound testing of this too

**Comment by markcarver** [comment]
This was initially/partially implemented in https://github.com/sequelpro/sequelpro/issues/1681

It would be nice if this could also support SSH query parameters as I suggested in https://github.com/sequelpro/sequelpro/issues/1681#issuecomment-597398812

**Comment by lonkle** [comment]
Yes, this (https://github.com/sequelpro/sequelpro/issues/1681#issuecomment-597398812)!

SSH URL Schema is what I need personally, will that be included in this next release?

**Comment by Jason-Morcos** [comment]
> Yes, this (https://github.com/sequelpro/sequelpro/issues/1681#issuecomment-597398812)!
> 
> 
> 
> SSH URL Schema is what I need personally, will that be included in this next release?

Support for opening URLs in the SSH URL schema is already supported by the latest App Store release of Sequel Ace.

As to support for sockets via url, that is not included in the app and likely will not until we resolve socket issues _and_ someone has time to write support for socket URLs.

**Comment by lonkle** [comment]
> Support for the mysql+ssh:// ssh URL schema is not currently written, as far as I'm aware, and thus will not be included in the next release of Sequel Ace unless someone writes this code and submits a PR. I would be happy to review such a PR, but don't believe this to be a priority at this time.

I don't have time for a PR right now, but I **am** passionate enough to add this. I'll have time to do so in 2021. Thanks for the update!

**Comment by will-ashworth** [comment]
Not sure why this was closed when there was a plan to revisit this in 2021. Can we re-open it? Support for specifying socket via `mysql://`-style URLs would be extremely helpful for easily integrating Sequel Ace with other external applications on a system 🤷‍♂️

I'm actually attempting the same thing with Local (by Flywheel), and cannot due to this limitation. While I can handle the JS/React side of things for Local's end of this via an addon, I am not savvy with the development language Sequel Ace uses. This addon for Local is working, minus this one part. 

This page outlines how this is supposed to work, though:

https://dev.mysql.com/doc/refman/8.0/en/connecting-using-uri-or-key-value-pairs.html

Thanks, and hopefully this is helpful! One-click access to be able to open a Local socket database without having to configure a separate connection for every site within Local would be a godsend. This is what's preventing that. Also, this really isn't just about Local; it's about any similar local webserver being able to access information via an established protocol (which we already have, but sounds like it's not fully supported in Sequel Ace yet) 😬

**Comment by Jason-Morcos** [comment]
Reopened but we really have other critical issues with sockets to fix before adding additional features. Sockets and the sandbox don't play nice together.

**Comment by brandondove** [comment]
> Not sure why this was closed when there was a plan to revisit this in 2021. Can we re-open it? Support for specifying socket via `mysql://`-style URLs would be extremely helpful for easily integrating Sequel Ace with other external applications on a system 🤷‍♂️
> 
> I'm actually attempting the same thing with Local (by Flywheel), and cannot due to this limitation. While I can handle the JS/React side of things for Local's end of this via an addon, I am not savvy with the development language Sequel Ace uses. This addon for Local is working, minus this one part.
> 
> This page outlines how this is supposed to work, though:
> 
> https://dev.mysql.com/doc/refman/8.0/en/connecting-using-uri-or-key-value-pairs.html
> 
> Thanks, and hopefully this is helpful! One-click access to be able to open a Local socket database without having to configure a separate connection for every site within Local would be a godsend. This is what's preventing that. Also, this really isn't just about Local; it's about any similar local webserver being able to access information via an established protocol (which we already have, but sounds like it's not fully supported in Sequel Ace yet) 😬

Heh. This is exactly why I created this ticket last year. Not sure there is a good solution for this based on this ticket's history.

**Comment by h1nds1ght** [comment]
My focus wouldn't be on sockets, I am more interested in passing the ordinary SSH connection details as query parameters, which has been already mentioned (https://github.com/sequelpro/sequelpro/issues/1681#issuecomment-597398812).

**Comment by Jason-Morcos** [comment]
@h1nds1ght PRs welcome :)

We have the syntax for a standard connection:
```
mysql://[user[:password]@][host[:port]][/database]
```

Someone could add a new schema/enhance the existing schema based substantially on this code already written.
Perhaps something like:
```
mysql://[user[:password]@][host[:port]][/database][?ssh_host=][&ssh_port=][&ssh_user=][&ssh_password=]
```

**Comment by h1nds1ght** [comment]
Exactly, I would suggest to add also a path to a possible ssh_key

```
mysql://[user[:password]@][host[:port]][/database][?ssh_host=][&ssh_port=][&ssh_user=][&ssh_password=][&ssh_key=]
```

and if ssh_key is given it is used,  otherwise ssh_password is assumed.

If I look into the original commit

https://github.com/sequelpro/sequelpro/commit/ec60a32215bb07f5ccd9b8061a88112985acaf8b

this now seems to be handled here

https://github.com/Sequel-Ace/Sequel-Ace/blob/main/Source/Controllers/SPAppController.m#L899

Unfortunately my knowledge about swift(?) is as limited as the question mark behind it.

While I could eventually handle the logic for the parameters, an even bigger problem would be to initiate the switch to the SSH tab

<img width="190" alt="image" src="https://user-images.githubusercontent.com/88188042/176533643-46296a0f-8a3e-457f-b809-a88bb91c2f96.png">

But maybe the original commit could point a way to it :man_shrugging:

**Comment by Jason-Morcos** [comment]
> While I could eventually handle the logic for the parameters, an even bigger problem would be to initiate the switch to the SSH tab
> 
> <img alt="image" width="190" src="https://user-images.githubusercontent.com/88188042/176533643-46296a0f-8a3e-457f-b809-a88bb91c2f96.png">
> 
> But maybe the original commit could point a way to it 🤷‍♂️

I think that would just be changing the line `[details setObject:@"SPTCPIPConnection" forKey:@"type"];` to `[details setObject:@"SPSSHTunnelConnection" forKey:@"type"];` for SSH-based connections





> Exactly, I would suggest to add also a path to a possible ssh_key
That would only work if Sequel Ace was already granted access to that key via the files tab of the app's preferences (because of the sandbox). If so, though, that would be fine

**Comment by h1nds1ght** [comment]
Finally I had some time for this

https://github.com/Sequel-Ace/Sequel-Ace/pull/1703

Query Parameters are stored in the dictionary. Therefore one can simply append the parameters by following the definitions in `SPDatabaseDocument.m`

```
mysql://[user[:password]@][host[:port]][/database][?ssh_host=][&ssh_port=][&ssh_user=][&ssh_password=][&ssh_keyLocation=][&ssh_keyLocationEnabled=]
```

**Comment by Jason-Morcos** [comment]
Completed in #1703
