### ISSUE TITLE
SSH bugs and UX bugs

### ISSUE THREAD

**Issue by dalikimail** [Sequel-Ace/Sequel-Ace#1146]
- Sequel Ace Version 3.3.3 3034
- Sequel Ace Source (App Store/GitHub/Homebrew): GitHub/Homebrew
- macOS Version: Big Sur 11.4
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.5.5-10.5.9-MariaDB
- macOS Localization: RU

Still really buggy application compared to Sequel Pro
Issues:
1) Can't establish two ssh connections to the same server (Sequel Pro perfectly does it)
2) After closing connection tab ssh connection is still alive. Sequel Pro have the same issue, but this doesn't inflict any real problem because you can establish new connection with Sequel Pro (you will have two ssh connections in `ps aux | grep ssh`). With Sequel Ace you can't do this because of the first problem, and you should manually kill ssh connection
3) If several connection tabs opened and there are some sql in Query, after closing left tab content of Query tab will move from right to left (as if you didn't closed left tab). Really annoying. I don't remember if such issue was in Sequel Pro (to be honest, there is terrible crashing of Pro when tab is closed, so I can't check it)
4) Moreover, after closing left tab you can't tell which tab is for which connection because something really weird starts to happen -- tab headers are good but database list and table list are from wrong tabs. It becomes completely impossible to work after closing tab, so, there are still no progress comparing with Sequel Pro

These are the most annoying bugs. Project is really good but there are a lot work to do. I hope that hotfixes will be published as soon as possible

**Comment by Jason-Morcos** [comment]
This project is fully open source. None of us get paid for the work we do here, but we do it because we enjoy it and only when our lives grant the time to do so. If you have specific problems with Ace, the best way to get them fixed is to attempt a solution and submit a pull request (PR) which I would be happy to critique and work with you on.

> Still really buggy application compared to Sequel Pro
> Issues:
> 
> 1. Can't establish two ssh connections to the same server (Sequel Pro perfectly does it)

I just tested and you definitely can establish two ssh connections to the same server. If you're really sure you can't, please file an issue report dedicated to this specific issue and include more detail about what "can't" means. Issues should be for a specific problem, not for "several problems".

> 2. After closing connection tab ssh connection is still alive. Sequel Pro have the same issue, but this doesn't inflict any real problem because you can establish new connection with Sequel Pro (you will have two ssh connections in `ps aux | grep ssh`). With Sequel Ace you can't do this because of the first problem, and you should manually kill ssh connection

Known issue, https://github.com/Sequel-Ace/Sequel-Ace/issues/811. Please don't open duplicate issues for known issues.

> 3. If several connection tabs opened and there are some sql in Query, after closing left tab content of Query tab will move from right to left (as if you didn't closed left tab). Really annoying. I don't remember if such issue was in Sequel Pro (to be honest, there is terrible crashing of Pro when tab is closed, so I can't check it)

https://github.com/Sequel-Ace/Sequel-Ace/issues/1056

> 4. Moreover, after closing left tab you can't tell which tab is for which connection because something really weird starts to happen -- tab headers are good but database list and table list are from wrong tabs. It becomes completely impossible to work after closing tab, so, there are still no progress comparing with Sequel Pro

https://github.com/Sequel-Ace/Sequel-Ace/issues/1056

> 
> These are the most annoying bugs. Project is really good but there are a lot work to do. I hope that hotfixes will be published as soon as possible

Like I said, happy to work with you if you'd like to contribute to the project :)

**Comment by bastones** [comment]
> If you have specific problems with Ace, the best way to get them fixed is to attempt a solution and submit a pull request (PR) which I would be happy to critique and work with you on.

Happy to critique other people's work, but not happy to receive it. Is that what you mean?

Sequel Ace's UI is slow and the software has so many bugs it's just becoming offensive. There is no excuse for this whether or not contributors are being "paid for the work we do". If you can't do something well, don't do it at all.

Sequel Pro was taken and made worse. What a bizarre world we live in: critical feedback is no longer tolerated and poor performance is rewarded.
