### ISSUE TITLE
Fulltext index support on InnoDB tables not handled properly for MariaDB 

### ISSUE THREAD

**Issue by najdanovicivan** [Sequel-Ace/Sequel-Ace#1156]
**Description**

supportsFulltextOnInnoDB is currently handled by checking that mysql version is greater than MySQL 5.6.4

I have MariaDB 10.4.17 and for some reason it is marked as MySQL 5.5.5 

This is from official docs on MariaDB site
Full-text indexes can be used only with MyISAM and Aria tables, from MariaDB 10.0.5 with InnoDB tables and from MariaDB 10.0.15 with Mroonga tables, and can be created only for CHAR, VARCHAR, or TEXT columns.

**Comment by Jason-Morcos** [comment]
Hmmmm we use the MySQL version comparisons for all things everywhere because MariaDB is supposed to have feature parity with its cross-marked MySQL version. We don't support mysql 5.5.x anymore at all.

I'm not sure of a way we can fix this - it seems tough to workaround your MariaDB version claiming it has feature parity with 5.5.5 but offering a 5.6.4 feature...

Any thoughts, @Kaspik?
