### ISSUE TITLE
WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED! is not resolved after removed known_hosts

### ISSUE THREAD

**Issue by KaitakuShiba** [Sequel-Ace/Sequel-Ace#1171]
- Sequel Ace Version (including build number): Version 3.3.3(build: 3034)
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: Big Sur 11.4
- Processor Type (Intel/Apple): Apple
- MySQL Version: 5.7.34
- macOS Localization: JA

**Description**
I can't connect ssh to mysql DB because `WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!` error raised after I removed known_hosts.
I connected using the Client~EC2(bastion host)~RDS configuration, and the startup status of EC2 and RDS is fine.
If I use another GUI MySQL client(ex: Sequel Pro), I can connect without any problem and I can also make an ssh connection to EC2 on my terminal app.
Is there some kind of cache here that works?I'd like to know how to solve it.

**Steps To Reproduce**
1.   Launch EC2 (bastion host、InstanceA) and RDS and make an ssh connection.
2.  Delete InstanceA, and then create another EC2(InstanceB) with the same IP address.
3.  Delete the IP information of the connection destination that is recorded in `~/.ssh/known_hosts`.
4.  I can login ssh in with a different fingerprint, but this app shows `WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!` and I can't connect.

**Comment by mfehr94** [comment]
@KaitakuShiba did you configure to sequel ace to use `~/.ssh/known_hosts` or does it use his internal `known_hosts` file?

**Comment by KaitakuShiba** [comment]
> @KaitakuShiba did you configure to sequel ace to use `~/.ssh/known_hosts` or does it use his internal `known_hosts` file?

Thank you, your question has helped me to solve this problem.
By default, the app is using the internal known_hosts.
So, in this case, Open  `Sequel Ace`-> `Preferences...` -> Click `Network Tab` -> Click `Unknown_hosts` -> Select my known_hosts file ex: `~/.ssh/known_hosts`

**Comment by Jason-Morcos** [comment]
For someone coming across this in the future, as mentioned above Sequel Ace does _not_ by default use your system known hosts file due the app sandbox. The error message you were getting about the host key should have included the full path to the actual file that Ace _was_ using which is dependent on your specific install of the app (it is in something called an app container). We need to add management of known hosts into the app at some point, but for now the best way to resolve this problem is to either edit the Sequel Ace known hosts file mentioned in the error itself, or do what @KaitakuShiba did above and switch the app to use your user known hosts.
