### ISSUE TITLE
Show table size in "TABLES" view

### ISSUE THREAD

**Issue by stefanskotte** [Sequel-Ace/Sequel-Ace#1179]
Hello,

I was wondering if there's a feature to show the approx table size on the list here ?

![screenshot_240](https://user-images.githubusercontent.com/521625/127226920-b3b73aa2-90f7-4692-bdc2-426e9abfac5a.png)

There's bound to be a performance hit, I know that - but it would be really useful to get this info.

**Comment by Jason-Morcos** [comment]
Hey there,

There's no feature to do that today. The little info panel in the bottom left corner should show counts for the actively selected table.

There could be an option to enable what you've described, but I would definitely aim for a feature like that to be disabled by default due to the performance implications you correctly mentioned.

Community PRs are welcome and are reviewed!

**Comment by stefanskotte** [comment]
Thanks for the quick reply :) - I will see if I can get time to make a PR for it.
