### ISSUE TITLE
"delete row" in context menu after sending an individual query

### ISSUE THREAD

**Issue by zarquon42** [Sequel-Ace/Sequel-Ace#1187]
Hi there,
showing the full content of a table I can delete and duplicate rows. I'd love to have this after sending a individual query. Especially the "relete row" functionality.

In my special case: I have to clean up da database that has duplicate entries. It's pretty easy to list them with a nice litte sql statement and would be a charm to get rid of the unwanted rows with a simple click.

**Comment by fredericgboutin-yapla** [comment]
FYI - 2 of my colleagues are migrating back to DBeaver because of this missing feature and the visible lack of support.

**Comment by Jason-Morcos** [comment]
Hi there, as Sequel Ace is free and open-source, you're right to note that we don't provide the same kind of support guarantees that come with commercial software. If you'd like to submit a pull request for this feature, I'd be happy to review it and likely merge it. We try out best to keep Sequel Ace at its best, but at the heart of Open Source is the community - the community can contribute to and enhance the app to make it ever better. Unfortunately, I'm not paid to work on this project and neither is anyone else. Sure, people can donate to Sequel Ace and we greatly appreciate these donations as they offset the costs of development, but it would be unreasonable to expect the same time commitments of work and support from this project that you would expect from something you're paying for. I hope that DBeaver works well for your colleagues and meets their needs :)

**Comment by fredericgboutin-yapla** [comment]
I don't "expect" anything, I'm letting the project knows what happened. I think there is valuable information in here about adoption (or lack thereof).

And TBH, this issue was tagged as "Feature request" but it was closed because of low activity. 

Personally I don't agree with that policy. If SequelAce community is seeking for features X and Y, you shouldn't close those issues, they should remain open and getting traction so they eventually get done because at some point, like you said, someone will finally decide to contribute to make it happen.
