### ISSUE TITLE
Sequel Ace doesn't use default SSH key for tunnelling, forcing the user to select a key

### ISSUE THREAD

**Issue by salvor-hardin** [Sequel-Ace/Sequel-Ace#129]
- Sequel Ace Version: 2.1.0
- macOS Version: 10.15.5
- MySQL Version: 5.7.30

**Description**
Sequel Ace doesn't automatically read the user's SSH keys to connect

**Steps To Reproduce**
Simply try to connect to a SSH host with Tunnel. You are forced to specify your SSH key, but the tool should automatically try to use the default key.

**Expected Behaviour**
When nothing specified, Sequel Ace should automatically try to use ~/.ssh/id_rsa
(same as Sequel Pro)

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Additional Context**
Sequel Pro didn't need for the user to select the default key.
<img width="380" alt="2020-06-28 at 14 17 37" src="https://user-images.githubusercontent.com/40695717/85948791-9d89e580-b94a-11ea-8dd6-fe29f7184400.png">

The only way to get this working with Sequel Ace is to manually select the default user's key, but this should be automatically used if none entered:
<img width="376" alt="2020-06-28 at 14 17 25" src="https://user-images.githubusercontent.com/40695717/85948789-9bc02200-b94a-11ea-860b-81707b39277d.png">

**Comment by Jason-Morcos** [comment]
Sequel Ace and Sequel Pro are very different in several ways at this point. One big one is that Sequel Ace is a sandboxed app (so it can be distributed on the Apple App Store). This is good because it means the app has a level of separation from your primary file system.

Sequel Ace simply can not access the .ssh directory unless you specifically select a key from this directory. That means that we cannot use anything from your .ssh directory by default. I know it's a little more annoying to have to select your keys manually, but on the bright side at least the app isn't crawling around your .ssh directory?

**Comment by salvor-hardin** [comment]
What about a "default" location for SSH key ( i.e. ~/.ssh/id_rsa ) so that is used for all connections unless other one specified for the specific connection?

This way we can setup this option ONCE and only change when is needed. Otherwise I'd have to do this for all of them...

**Comment by Jason-Morcos** [comment]
@salvor-hardin working on it! See #68/#144

**Comment by Jason-Morcos** [comment]
> Would it be possible to work with a SSH agent as well? I just started testing 1Password 8 beta and they configure the agent like that in `~/.ssh/config`:
> 
> ```
> Host *
>   IdentityAgent "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
> ```
> 
> But naturally this doesn't work out-of-the-box (nor with configuration) with Sequel Ace...

I don't think I quite understand what's being asked here. For new requests, please open a new issue. Closed issues are generally not monitored and it tends to work better to have new discussions in new issues to keep conversations tight and clean. Thanks!

**Comment by ctissier** [comment]
I believe @xperseguers writes about the 1password8's new feature allowing its users to store ssh keys in 1password instead of the classic "id_rsa"-ish ssh key files.

Apparently, Sequel Ace doesn't natively support the use of other ssh agents than the default (or built-in) one.

I opened a feature request here #1434 .

**Comment by ctissier** [comment]
> Would it be possible to work with a SSH agent as well? I just started testing 1Password 8 beta and they configure the agent like that in `~/.ssh/config`:
> 
> ```
> Host *
>   IdentityAgent "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
> ```
> 
> But naturally this doesn't work out-of-the-box (nor with configuration) with Sequel Ace...

Hello,

I made it work by simply removing the path to the now deleted key file in the "Preference > Files" dialog box.

![Capture d’écran 2022-03-25 à 10 44 43](https://user-images.githubusercontent.com/4759478/160096739-d107fd08-420d-4e61-8aec-d1c2eddea072.png)

It now uses 1password8's ssh agent. Great.
