### ISSUE TITLE
can't run project on my mac 

### ISSUE THREAD

**Issue by xyhuangjia** [Sequel-Ace/Sequel-Ace#142]
step:
1、git clone project on my desktop, 
2、open folder and run sequel-ace.xcodeproj
3、can't run

need document tell me how to run app on my mac

**Comment by Jason-Morcos** [comment]
Hi, please download Sequel Ace from the App Store to run it on your Mac. Otherwise, you can download the latest release from the github repository's releases (.zip file)

If you're looking to try to get started developing/contributing, please take a look at Apple's documentation at developer.apple.com!
