### ISSUE TITLE
Error while reading connection data file

### ISSUE THREAD

**Issue by froboy** [Sequel-Ace/Sequel-Ace#1423]
- Sequel Ace Version (including build number): 3.5.1 build 20031
- Sequel Ace Source (App Store/GitHub/Homebrew): Github (tested with App store also)
- macOS Version: 12.3, 12.2
- Processor Type (Intel/Apple): Apple
- MySQL Version: mariadb:10.4
- macOS Localization: English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?** yes

**Description**

**Steps To Reproduce**
1. Attempt to connect to a database using https://github.com/docksal/addons/blob/master/sequelace/sequelace
2. Sequelace fails to open the file with "Error while reading connection data file"

**Expected Behaviour**

The connection file should be read and a connection opened.

**Related Issues**

**Additional Context**

<img width="260" alt="error_reading" src="https://user-images.githubusercontent.com/238201/158681605-d72950c2-1521-4fd7-9b78-477832e1c673.png">

This worked before, but some combination of updates has broken it. I've tried reverting the sequelace version to a few months ago but that didn't resolve the issue. The file i'm attempting to connect with is below (with identifying info removed):

<details>
<summary>docksal-sequelace-12345.spf</summary>

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>ContentFilters</key>
  <dict/>
  <key>auto_connect</key>
  <true/>
  <key>data</key>
  <dict>
    <key>connection</key>
    <dict>
      <key>database</key>
      <string>default</string>
      <key>host</key>
      <string>mysite.docksal</string>
      <key>name</key>
      <string>my-site</string>
      <key>user</key>
      <string>user</string>
      <key>password</key>
      <string>user</string>
      <key>port</key>
      <integer>127.0.0.1:55003</integer>
      <key>rdbms_type</key>
      <string>mysql</string>
    </dict>
    <key>session</key>
    <dict/>
  </dict>
  <key>encrypted</key>
  <false/>
  <key>format</key>
  <string>connection</string>
  <key>queryFavorites</key>
  <array/>
  <key>queryHistory</key>
  <array/>
  <key>rdbms_type</key>
  <string>mysql</string>
  <key>version</key>
  <integer>1</integer>
</dict>
</plist>
```

</details>

**Comment by Jason-Morcos** [comment]
Seems like this bug should be reported to the docksal repo and not the SA repo? One can export an existing connection and compare it to the connection file being generated by docksal to figure out what changes docksal needs to make. We'd be happy to fix this if it turns out there's a Sequel Ace bug to address, but we don't offer official support for third-party tools and there doesn't appear to be a known issue with connection importing in general as far as I know.

**Comment by Jason-Morcos** [comment]
Closing this issue for now - happy to reopen if the docksal folks find a bug in Sequel Ace that needs to be addressed.

**Comment by danshumaker** [comment]
For what it's worth I still get this error with docksal and the sequelace docksal addon ( https://github.com/docksal/addons/blob/master/sequelace/sequelace ) .

When I look at the spf file that it generates it looks good and the format has not actually changed.

As far as "Third party tools support" is concerned, I'd look at it like supporting the opening of spf files.  Is that still supported?

If there is a good format that is proven to work with sequelace, then we'll (us docksal folks) adjust the sequelace docksal addon to generate that format.  

Sequel Ace Version: Version 3.5.3, Build 20035.   

I imagine it's an issue with Docker and not docksal, but it's hard to confirm port conflicts and low level networking (sockets verses ssh verses dns) communications.

**Comment by danshumaker** [comment]
also related: https://github.com/Sequel-Ace/Sequel-Ace/issues/1330

**Comment by Jason-Morcos** [comment]
If I had to guess, the .spf file is probably missing some keys required by the latest versions of Ace. I would try exporting a connection that works and comparing the differences between that and the output of the add-on.

Notably, right off the bat I see a key missing which could perhaps be the problem:
```
			<key>allowDataLocalInfile</key>
			<integer>0</integer>
```

**Comment by danshumaker** [comment]
yeah, there is something else going on.  I'd say something in the last 6 months broke a port or dns issue or something. Because now, non of my projects can connect through SequelAce.

I appreciate your feedback @Jason-Morcos .   Unfortunately, I upgraded to Mac Arm64 recently 3months ago, as well as renamed all my docksal sites  from *.docksal to *.fin due to a deprecation in the *.docksal dns name.   

Then I also noticed that my VPN expressvpn also has gone through four or five upgrades and I have seen my system dns settings for my eth01 connection change several times...   

And then there is also docker and docker-composer version updates that have been happening...   So many variables are changing.   

I do love the functionality that it provides and so will keep pluging away at it.

**Comment by froboy** [comment]
I tried adding this to an existing file to no avail.

> Notably, right off the bat I see a key missing which could perhaps be the problem:
> 
> ```
> 			<key>allowDataLocalInfile</key>
> 			<integer>0</integer>
> ```

I'm pretty sure this has to do with https://github.com/docksal/docksal/issues/1683#issuecomment-1150563138 and isn't an issue with Sequel Ace but with Docksal. I was able to get a broken connection working by running `fin restart db` then `fin sequelace` again. Hope that helps someone who lands here.

**Comment by danshumaker** [comment]
A thousand thanks @froboy , the `fin restart db` did the trick for me as well. This is the best news I've heard all week!  So stoked!

**Comment by mokapost** [comment]
This does appear to be related to the issue @froboy linked. I ran into this a couple of days ago as well and had narrowed it down to `$PORT` in Docksal's Sequel Ace addon including `127.0.0.1:` instead of just the port number because it expects (and filters out) `0.0.0.0:`. I was getting past it by modifying the addon, but this seems like a better workaround. Thanks to you both!
