### ISSUE TITLE
ON DELETE RESTRICT misses RESTRICT

### ISSUE THREAD

**Issue by cappadaan** [Sequel-Ace/Sequel-Ace#1427]
- Sequel Ace Version (including build number): 3.4.5
- Sequel Ace Source (App Store/GitHub/Homebrew): Github
- macOS Version: 12.3
- Processor Type (Intel/Apple): Intel
- MySQL Version: MariaDB 10.7.3
- macOS Localization: NL

Create any table with a relation like this:

ON UPDATE CASCADE ON DELETE RESTRICT

result of 9 relations:

Sequel Ace 

<img width="140" alt="Screenshot 2022-03-21 at 14 33 21" src="https://user-images.githubusercontent.com/25279400/159273103-d59d4073-0e0e-4c95-9485-d66da2808e6d.png">

HeidiSQL on windows

![image_2022_03_21T13_34_06_295Z](https://user-images.githubusercontent.com/25279400/159273073-69c2589b-7ba4-4439-b9b2-6d2228436eac.png)

+

Export via tab Table Info in Sequel Pro gives for all 9 relations:

ON DELETE CASCADE ON UPDATE CASCADE

**Comment by Jason-Morcos** [comment]
This looks to be a UI bug, but a pretty bad one at that because of how misleading it is

**Comment by Jason-Morcos** [comment]
@gduh or @luis- did one of you recently make some changes to parseCreateStatement in SPTableData? I imagine this behavior has been this way forever, but perhaps one of you would like to take a stab at a fix for this if you're already familiar with the code!

**Comment by gduh** [comment]
@Jason-Morcos 
I did not make any changes to this method, but I have worked on the relation concept before. I will try to solve this issue.

**Comment by gduh** [comment]
Well, it's not really a UI bug.

In fact, `DELETE RESTRICT` is the default behavior.
So it is possible to declare it in a `CREATE TABLE` query, for example: 

    CREATE TABLE `master` (
      `id` smallint(6) NOT NULL AUTO_INCREMENT,
      `name` varchar(30) NOT NULL,
      `code` tinyint(4) NOT NULL DEFAULT 0,
      PRIMARY KEY (`id`),
      KEY `code` (`code`),
      CONSTRAINT `fk_priv` FOREIGN KEY (`code`) REFERENCES `details` (`id`) ON UPDATE CASCADE DELETE RESTRICT
    ) ENGINE=InnoDB;

But, when using the query `show create table master;` or any other `DUMP`, in the output, inside the `CONSTRAINT` the `DELETE RESTRICT`is not specified: 

    CONSTRAINT `fk_priv` FOREIGN KEY (`code`) REFERENCES `details` (`id`) ON UPDATE CASCADE

If the option is different from `DELETE RESTRICT`, for example `DELETE CASCADE`, the output will be completed with the option: 

    CONSTRAINT `fk_priv` FOREIGN KEY (`code`) REFERENCES `details` (`id`) ON UPDATE CASCADE DELETE CASCADE

That's why, in the first case, SACE does not display `RESTRICT` while in the second case, SACE display `CASCADE`correctly.

To be sure about the option used, the following query explicitly shows the differents values : 

    SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS

<img width="183" alt="image" src="https://user-images.githubusercontent.com/15440947/160291309-43b7badc-290e-4d38-b1cc-302be08daa7a.png">

From this point, I see 2 options : 
- By default, we can consider that if `DELETE XXXXXX` is not present, SACE displays `RESTRICT`. The solution is simpler to implement.
- We can use `SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS` query to be sure which option to display. This solution is safer, but a little more complex.

I think the second is better, particularly if the default option changes in a future version or if MariaDB deviates from Mysql or whatever.
@Jason-Morcos  What do you prefer before I start the change ?

**Comment by Jason-Morcos** [comment]
Thanks for all the investigation, @gduh! I agree with your assessment, @gduh. I agree the second option is the better option! But, I also am starting to wonder if we should make a change at all here? Is displaying that piece of information for every row really useful if it's just the default value from the database? I think, perhaps, we should leave this as it is/deprioritize this issue. Thoughts, @Sequel-Ace/all?

**Comment by Jason-Morcos** [comment]
Some useful info from the docs: 

https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html
>For an ON DELETE or ON UPDATE that is not specified, the default action is always NO ACTION.
As the default, an ON DELETE NO ACTION or ON UPDATE NO ACTION clause that is specified explicitly does not appear in [SHOW CREATE TABLE](https://dev.mysql.com/doc/refman/8.0/en/show-create-table.html) output or in tables dumped with [mysqldump](https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html). RESTRICT, which is an equivalent non-default keyword, appears in [SHOW CREATE TABLE](https://dev.mysql.com/doc/refman/8.0/en/show-create-table.html) output and in tables dumped with [mysqldump](https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html).

I tend to believe that if it's not in the create statement/is the database default, we shouldn't display it in the front-end. Similar to the default values discussion we had

**Comment by cappadaan** [comment]
NO ACTION is visible, which is not consistent. 

<img width="128" alt="Screenshot 2022-03-29 at 09 38 26" src="https://user-images.githubusercontent.com/25279400/160559016-d6d99b21-53ef-4f08-a884-1484ab4b06ef.png">

**Comment by Jason-Morcos** [comment]
It sounds like the best option here is to make no change. If someone has an idea for a good change that would be consistent with expectations and MySQL standards, please suggest it!

**Comment by cappadaan** [comment]
NO ACTION is visible, which is not consistent. Just leave it empty, it is very confusing.

**Comment by Jason-Morcos** [comment]
I'm really quite confused at this point. Is there another way you could describe the issue? Does the display match the result of `SHOW CREATE TABLE...`?
