### ISSUE TITLE
"Show warning before executing a query" should apply to changes to table structure as well

### ISSUE THREAD

**Issue by MikeRich88** [Sequel-Ace/Sequel-Ace#1449]
- Sequel Ace Version (including build number): 3.5.2 Build 20033
- Sequel Ace Source (App Store/GitHub/Homebrew): github
- macOS Version: mojave
- Processor Type (Intel/Apple): INTEL INSIDE
- MySQL Version: 8.0.27
- macOS Localization: english

**Description**
same as steps below

**Steps To Reproduce**
1. Ensure "Show warning before executing a query" preference is checked
2. Uncheck "Allow Null" on a column's schema. 
3. A query is executed (ALTER TABLE) but no warning is shown.

**Expected Behaviour**
ALTER TABLE is a query. It should have shown me a warning. Instead, it bricked my site until I went in and killed the query in the command line. (because its a large table and you aren't using LOCK=NONE in ALTER query)

**Related Issues**
Could not find

**Additional Context**
n/a

**Comment by Jason-Morcos** [comment]
Show warning before query was meant to only apply when changing the content of the table. I agree this is misleading, however, and should also apply when editing table _structure_ too.

**Comment by mariog0ncalves** [comment]
Has this issue ever been addressed? If so, i think I've found another case where this isn't being applied.

This week I've mistakenly double clicked on a table instead of the search bar, pasted the table name that i wanted to search for and ended up renaming a whole table without any message being shown. (which is a behaviour that i wasn't aware of)

Only after seeing that my production environment was down, and checking the query logs I did find out why.
