### ISSUE TITLE
Constantly losing connection to localhost during import

### ISSUE THREAD

**Issue by felix822** [Sequel-Ace/Sequel-Ace#1485]
Sequel-Ace version: 3.5.2  (Build 20033)
macOS version: Monterey 12.4 
Device: M1 MacBook Pro

I'm trying to import tables from a SQL dump I made on my old laptop. The app keeps losing connection to the localhost during the import, and preventing the import to complete. After I killed the app and re-opened it, it will no longer connect to my localhost at all. Is there something I can do to fix this problem? Thanks. 

<img width="647" alt="Screen Shot 2022-06-27 at 2 58 14 PM" src="https://user-images.githubusercontent.com/2913621/176017755-91f4eda7-ff1a-4f3f-ab19-28c5b987e99d.png">

<img width="359" alt="Screen Shot 2022-06-27 at 3 11 22 PM" src="https://user-images.githubusercontent.com/2913621/176017811-a9bbd938-9ae9-49ec-a7f4-5a60a5974f9d.png">

**Comment by Jason-Morcos** [comment]
Is it possible the file you're importing is a full replacement to the database you're connected to? In other words, are you dropping the database you're connected to in the process of replacing it? If so, I would potentially try connecting to a different DB on the same MySQL instance (potentially connected as root) because I bet this weird behavior is caused by trying to drop the database you're actively connected to.

**Comment by felix822** [comment]
It was something with the older version of MariaDB. Once I installed the latest, everything was fixed. Thank you though.
