### ISSUE TITLE
beginSheetModalForWindow is deprecated

### ISSUE THREAD

**Issue by jamesstout** [Sequel-Ace/Sequel-Ace#15]
`- (void)beginSheetModalForWindow:(NSWindow *)window modalDelegate:(nullable id)delegate didEndSelector:(nullable SEL)didEndSelector contextInfo:(nullable void *)contextInfo API_DEPRECATED("Use -beginSheetModalForWindow:completionHandler: instead", macos(10.3,10.10)`

It's used all over the place.

**Comment by gboudreau** [comment]
Maybe `SPBeginAlertSheet` could be used, instead of `NSAlert`..? Not sure why some alerts use `NSAlert`, and others `SPBeginAlertSheet`..?
If `SPBeginAlertSheet` has some advantage over `NSAlert`, it might be cleaner to use that class everywhere, in order to only have one place to change, if the `NSAlert` changes again later.

**Comment by Kaspik** [comment]
We should prioritize this.

The main reason for this is that 'beginSheetModalForWindow:modalDelegate:didEndSelector:contextInfo:' uses `contextInfo` which is problematic for ARC and will block us soon in conversion to ARC enabled project.

### TODO:
- replace: 'beginSheetModalForWindow:modalDelegate:didEndSelector:contextInfo:'
- replace with: `-beginSheetModalForWindow:completionHandler:`

### NOTES:
- ideally make multiple smaller PRs for different files and places so more people can work on this together without conflicts and also so we have smaller changes in our project that we can test.

**Comment by Jason-Morcos** [comment]
I believe this is done
