### ISSUE TITLE
longitude/latitude order when inserting GIS data has changed in MySQL 8.0

### ISSUE THREAD

**Issue by daesan** [Sequel-Ace/Sequel-Ace#1509]
- What version of Sequel-Ace are you using? 3.5.2
- What version of macOS are you running on? 12.3.1
- What device(s) are you using Sequel-Ace on? MacBook Air M1

Thank you for this excellent MySQL client app. I've been using the app since CocoaMySQL era and I am very grateful that this great app continues to thrive. 👍

One of the GIS related changes in MySQL 8.0 is default longitude/latitude order when inserting GIS data has changed from longitude/latitude to latitude/longitude.

In other words, ST_GeomFromText('POINT(10.3958 63.4269)', 4326) in MySQL 5.7 should be changed to ST_GeomFromText('POINT(63.4269 10.3958)', 4326) in MySQL 8.0. (Note that longitude/latitude order is reversed.)

Or, we could use ST_GeomFromText('POINT(10.3958 63.4269)', 4326, 'axis-order=long-lat')

Due to this change, if I update a row in MySQL 8.0 database using Sequel Ace, GIS data column is updated with reversed latitude/longitude values.

--

Please refer to the following blog post from MySQL development team:

https://dev.mysql.com/blog-archive/axis-order-in-spatial-reference-systems/

**Comment by Jason-Morcos** [comment]
@luis- any chance you'd want to take a stab at switching the order based on MySQL version? Shouldn't be a huge lift, just gotta dig through the code and figure out where it's happening and then switch based on the DB version

**Comment by luis-** [comment]
Taking a trip this weekend, but if this is still looking for a dev next week, I can give it a shot.

**Comment by luis-** [comment]
Hey @Jason-Morcos! 

I have a branch with changes, so far manual testing is going well but wanted to get your feedback on the changes before I moved forward with a PR. You can see the changes so far in linked branch [here](https://github.com/Sequel-Ace/Sequel-Ace/compare/main...luis-:Sequel-Ace:bugfix/1509).

The general approach I went with is making `SPMySQLResult` and `SPMySQLGeometryData` aware of server major version.
Ans swapping the `x` & `y` coordinates of a point as we extract the from the `Internal Geometry Storage Format`. But it's not a blanket rule for all points if MySQL version == 8. According to the blog linked in original post: 
> MySQL 8.0 follows this recommendation. If the SRS is defined as latitude-longitude, MySQL treats it as latitude-longitude. If the SRS is defined as longitude-latitude, MySQL treats it as longitude-latitude.

From looking at the SRS using `use information_schema; select SRS_NAME, SRS_ID, DEFINITION from ST_SPATIAL_REFERENCE_SYSTEMS\G` I found that the swapping would apply to all but 8 `SRID`s so for now I hardcoded that list in my initial approach. Probably not the most ideal solution but for now I kept it simple.

As an alternative approach I tried passing server version to `- (NSString *)wktString` of `SPMySQLGeometryData`  but found that it is used from more places compared to where `SPMySQLResult` /`SPMySQLGeometryData` is initialized so that approach was getting much more messy.

**Comment by Jason-Morcos** [comment]
Hey, @Luis-, thank you for working on this!

I think that overall approach makes sense. @Kaspik do you have any thoughts here?

**Comment by Kaspik** [comment]
LGTM
