### ISSUE TITLE
Add option in Preferences to automatically enable filter content in table Content view

### ISSUE THREAD

**Issue by nexbridge** [Sequel-Ace/Sequel-Ace#1517]
I use table filters all the time (as I imagine many do), so it would be nice not to have to manually enable them every time I open a new tab/window.

**Comment by Jason-Morcos** [comment]
As a note, the Command+F keyboard shortcut should work to quickly show/hide the filters

**Comment by nexbridge** [comment]
OK that's helpful, thanks - it doesn't display the shortcut under Table -> Filter Content, so would it be a good idea to add that?

**Comment by Jason-Morcos** [comment]
> OK that's helpful, thanks - it doesn't display the shortcut under Table -> Filter Content, so would it be a good idea to add that?

Good idea - it does show that on hover, not sure why it doesn't show it on the menu option itself. My guess is because the keystroke is actually bound outside the menu bar.

**Comment by nexbridge** [comment]
Just realised that it only works in Content view so that may be why it's not listed as a general shortcut in the menu.

**Comment by DannyJJK** [comment]
> > OK that's helpful, thanks - it doesn't display the shortcut under Table -> Filter Content, so would it be a good idea to add that?
> 
> Good idea - it does show that on hover, not sure why it doesn't show it on the menu option itself. My guess is because the keystroke is actually bound outside the menu bar.

I think it might not show it on the menu option because Command+F is assigned to Edit -> Find -> Find… in the menu bar, which also opens the filters on the content view.

**Comment by nexbridge** [comment]
> I think it might not show the shortcut on the Table -> Filter Content menu option because Command+F is assigned to Edit -> Find -> Find… in the menu bar, which also opens the filters on the content view.

Good point - I'll raise that as a separate issue.

**Comment by nexbridge** [comment]
Why is this being marked as stale?  Just because a feature request hasn't been added yet doesn't mean it should be closed!

**Comment by nexbridge** [comment]
@Jason-Morcos Why is this being marked for closure? Just because a feature request hasn't been actioned yet doesn't mean it should be closed!

**Comment by Jason-Morcos** [comment]
> @Jason-Morcos Why is this being marked for closure? Just because a feature request hasn't been actioned yet doesn't mean it should be closed!

Hi, Stale bot marks issues stale that have little passion in the community. An issue being marked stale definitely doesn't mean it's not important - but it means that there doesn't appear to be interest within the community to make a feature/fix happen. We all work on this project for free - nobody gets paid. Things only get worked on when there's passion around them and someone willing to do that work. I think stale bot comes from an understanding that having issues sit open in the issue backlog makes it harder for issues with broad scope/passion to stand out and get the attention they deserve. I hope this doesn't come across as not caring about users in any way. The very fact this project exists is because a few folks got tired of all the bugs in Sequel Pro and decided to fix them for themselves and everyone else. Unfortunately, free, open source software doesn't come with the same professional support that a paid product is expected to - we all have day jobs and families that have to come first.

I encourage you to take a stab at doing this yourself! I'm more than happy to review any pull request submitted to Sequel Ace
