### ISSUE TITLE
Tab-Context Rows (Count) in Table is wrong

### ISSUE THREAD

**Issue by neumanniTech** [Sequel-Ace/Sequel-Ace#1545]
- Sequel Ace Version (including build number): 3.5.2 20033
- Sequel Ace Source (App Store/GitHub/Homebrew): Homebrew
- macOS Version: 12.5.1 (21G83)
- Processor Type (Intel/Apple): Intel
- MySQL Version: 10.6.0 MariaDB

**Description**
When you are in the Content Section, the count of Rows in Table is wrong. It says for Example
Rows 1 - 1000 of -370.753 from table.
![content-tab](https://user-images.githubusercontent.com/74491794/186070670-f80ebf77-a824-4fce-8d76-cf8d5c30f199.png)

When you run a simple SQL count query, you get for example 365.557.
![sql](https://user-images.githubusercontent.com/74491794/186070666-9776f651-352d-4f57-bacd-84d37e3602d1.png)

**Steps To Reproduce**
1. Create a table
2. Import data > 300.000
3. Compare Content Tab rows with simple mysql count

**Expected Behaviour**
The Count in Context must be the same as running a simple SQL count query.

**Comment by Jason-Morcos** [comment]
This is expected behavior.
MySQL doesn't cache the exact count of rows in a table (for efficiency) but caches an approximate count (thus the ~). That is what Ace shows for efficiency until/unless you do an actual count query which is slow (in general) on large tables.

There's an option in Sequel Ace's Preferences under the "Tables" tab to change the "table row counts" behavior to always get row counts though if you'd like to always see the exact count :)
