### ISSUE TITLE
Cmd-f shortcut not displaying correctly in menu

### ISSUE THREAD

**Issue by nexbridge** [Sequel-Ace/Sequel-Ace#1547]
- Sequel Ace Version: 3.5.2 (build 20033)
- Sequel Ace Source: App Store
- macOS Version: 12.5
- Processor Type: Intel

Currently the cmd-f shortcut opens a Find window if you're e.g. on the Query view or enables filters if you're on the Content view, however in the dropdown menus at the top the shortcut is only listed next to Edit -> Find -> Find and not next to Table -> Filter Content.  It may be that macOS only allows a given shortcut to be in one place in the menus, in which case there would seem to be a couple of ways to resolve it:

1. Cause the menus to dynamically update (if that's possible), i.e. show the cmd-f shortcut next to Table -> Filter Content when in the Content view and next to Edit -> Find -> Find when in the Query view.
2. Change the shortcut for enabling filters to something else that's not currently in use so as to avoid the conflict.

**Comment by nexbridge** [comment]
Why is this being marked for closure?  Just because a bug hasn't been fixed yet doesn't mean it should be closed!

**Comment by nexbridge** [comment]
@Jason-Morcos Why is this being marked for closure? Just because a bug hasn't been fixed yet doesn't mean it should be closed!

**Comment by Jason-Morcos** [comment]
This is a very very minor bug. The cmd+f shortcut works; macOS users are familiar with the shortcut; the only issue is the shortcut not showing properly in the menu bar.

Stale bot marks issues stale that have little passion in the community. An issue being marked stale definitely doesn't mean it's not important - but it means that there doesn't appear to be interest within the community to make a feature/fix happen. We all work on this project for free - nobody gets paid. Things only get worked on when there's passion around them and someone willing to do that work. I think stale bot comes from an understanding that having issues sit open in the issue backlog makes it harder for issues with broad scope/passion to stand out and get the attention they deserve. I hope this doesn't come across as not caring about users at all. The very fact this project exists is because a few folks got tired of all the bugs in Sequel Pro and decided to fix them for themselves and everyone else. Unfortunately, free, open source software doesn't come with the same professional support that a paid product is expected to - we all have day jobs and families that have to come first.

I encourage you to take a stab at fixing this bug yourself. I am very happy to review any pull request submitted to the repo.

Of the two options you suggested, I would lean towards option 2 because I think option 1 is bug prone with the way macOS binds keyboard shortcuts.

**Comment by nexbridge** [comment]
> I think stale bot comes from an understanding that having issues sit open in the issue backlog makes it harder for issues with broad scope/passion to stand out and get the attention they deserve.

There must be a better way to do this - having bug reports "expire" without being fixed seems to undermine the principles of bug reporting.  Is marking issues as "low priority" not enough already?  To be honest it discourages people like me to "invest" in the project by taking the time to identify bugs and provide steps to reproduce them if our efforts get wasted if no one happens to respond within a month (which is really not long).  Not everyone is skilled in Objective C, so for some of us this is the best that we can do to contribute to the project, but it really isn't worth it if our efforts get junked after a month.  Thank you for taking the time to respond though - I really do appreciate the efforts that you, Kaspik and others make on this project.  If I could do more I would, but for now the best I can do is to try to identify bugs (however minor) and report them as clearly as I can - if some of them get left on the backburner for a while then that's fine, but until they're fixed they shouldn't be closed!

**Comment by Kaspik** [comment]
The problem is that we override the default "Find" in "Edit" -> "Find" action and we don't use the action in "Table" in the menu. Both have the same shortcut CMD+F, but we can't have the shortcut shown for both in the menu. We would have to add another shortcut.

**Comment by nexbridge** [comment]
Thanks Kaspik - it might be simplest to just change the shortcut then, as unless you happen to know (and why would you?) that cmd-f enables filters there's nothing in the menu bar to tell you that.
