### ISSUE TITLE
Help Menu items are all disabled on the Connection Window

### ISSUE THREAD

**Issue by 9ae8sdf76** [Sequel-Ace/Sequel-Ace#1555]
- Sequel Ace Version (including build number): 3.5.3 Build 20035
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store -> Self Updating
- macOS Version: 12.5.1 (21G83)
- Processor Type (Intel/Apple): Intel
- MySQL Version: N/A
- macOS Localization: en_US

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes, still present.

**Description**
Help Menu items are all disabled on the Connection Window.

**Steps To Reproduce**
1. Open a new Connection Window
2. Click the Help menu

**Expected Behaviour**
All Help menu items should be enabled for use.

**Related Issues**
Could not find any.

**Additional Context**
Version 3.5.3
Build 20035

**Comment by 9ae8sdf76** [comment]
Can we not use the stale bot? It's not my fault everyone is too busy to look at this. But, that shouldn't mean that my issue is not important. All stale bot does is give a false sense of productivity by giving the illusion of fewer issues in queue, and as a user it instills the notion that the developers genuinely couldn't care less about their users. /rant

**Comment by Jason-Morcos** [comment]
> Can we not use the stale bot? It's not my fault everyone is too busy to look at this. But, that shouldn't mean that my issue is not important. All stale bot does is give a false sense of productivity by giving the illusion of fewer issues in queue, and as a user it instills the notion that the developers genuinely couldn't care less about their users. /rant

Hi there,

An issue being marked stale definitely doesn't mean it's not important - but it means that there doesn't appear to be interest within the community to make a feature/fix happen. We all work on this project for free - nobody gets paid. Issues aren't "in the queue", things only get worked on when there's passion around them and someone willing to do that work. I think stale bot comes from an understanding that having issues sit open in the issue backlog makes it harder for issues with broad scope/passion to stand out and get the attention they deserve. I hope this doesn't come across as not caring about users at all. The very fact this project exists is because a few folks got tired of all the bugs in Sequel Pro and decided to fix them for themselves and everyone else. Unfortunately, free, open source software doesn't come with the same professional support that a paid product is expected to - we all have day jobs and families that have to come first.
