### ISSUE TITLE
Stored Procedure not returning all rows

### ISSUE THREAD

**Issue by christatedavies** [Sequel-Ace/Sequel-Ace#1579]
- Sequel Ace Version (including build number): 4.0.0 (20037)
- Sequel Ace Source Can't remember. It updates from within. 
- macOS Version: 12.6
- Processor Type (Intel/Apple): Intel
- MySQL Version: 10.3.34-MariaDB-0ubuntu0.20.04.1
- macOS Localization: English

**Description**
I have created a stored procedure to loop through all databases on my server, run query and output results. SequelAce does not return ALL the results.

**Steps To Reproduce**
1. Create test database: (All email addresses are made up)

```sql
CREATE SCHEMA IF NOT EXISTS piggy_client_a;

CREATE TABLE piggy_client_a.user (
  id INT(11) NOT NULL AUTO_INCREMENT,
  fullname VARCHAR(30) DEFAULT NULL,
  email VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

INSERT INTO piggy_client_a.user (fullname, email) VALUES
("chris davis", "chris@something.com"),
("chris td", "chris@something.com"),
("bob sinclair", "bob@spectrum.net"),
("frank sidebottom", "frank@bighead.com");

CREATE SCHEMA IF NOT EXISTS piggy_client_b;

CREATE TABLE piggy_client_b.user (
  id INT(11) NOT NULL AUTO_INCREMENT,
  fullname VARCHAR(30) DEFAULT NULL,
  email VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

INSERT INTO piggy_client_b.user (fullname, email) VALUES
("fanny adams", "chris@elsewhere.net"),
("colin furry", "colin@something.com"),
("chris grumps", "grumpy@htom.com"),
("tracey singer", "trace@email.com");

CREATE SCHEMA IF NOT EXISTS piggy_client_c;

CREATE TABLE piggy_client_c.user (
  id INT(11) NOT NULL AUTO_INCREMENT,
  fullname VARCHAR(30) DEFAULT NULL,
  email VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

INSERT INTO piggy_client_c.user (fullname, email)VALUES
("mary qos", "mary@comms.com"),
("curtis jackson", "curtis@something.com"),
("christine motor", "chrissy@live.net"),
("tom peters", "tom@peters.org");
```

Okay, so I have three databases with the same table in and some rows in each. In each database, there is at least one user with the `fullname` beginning with "ch"

I create a stored procedure to run my query(ies):

```sql
DELIMITER $$
DROP PROCEDURE IF EXISTS `find_user`$$

CREATE PROCEDURE `find_user`(IN partial_name VARCHAR(20))
BEGIN

    DECLARE database_name VARCHAR(128) DEFAULT '';
    DECLARE non_found INTEGER DEFAULT 0;

    DECLARE database_list 
        CURSOR FOR 
            SELECT SCHEMA_NAME FROM information_schema.SCHEMATA 
            WHERE SCHEMA_NAME LIKE "piggy_client_%"
            ORDER BY SCHEMA_NAME ASC;

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET non_found = 1;

    OPEN database_list;

    check_table: LOOP

        FETCH database_list INTO database_name;

        IF non_found = 1 THEN 
            LEAVE check_table;
        END IF;

        SET @sql = CONCAT('SELECT "',database_name,'" AS db_name, fullname,email FROM ',database_name,'.user WHERE trim(fullname) like "%',partial_name,'%"');

        PREPARE db_statement FROM @sql;
        EXECUTE db_statement;
        DEALLOCATE PREPARE db_statement;

    END LOOP check_table;

    CLOSE database_list;

END$$

DELIMITER ;
```
3. When I run said procedure, I expect to see all matching databases with corresponding rows. But this is the output of SequelAce:

<img width="461" alt="Screenshot 2022-10-20 at 09 20 38" src="https://user-images.githubusercontent.com/1114343/196895501-81c8e32e-668a-4476-9324-12544d24760a.png">

4. If I run the same procedure from within the MySQL console, I get the desired results:

<img width="581" alt="Screenshot 2022-10-20 at 09 22 01" src="https://user-images.githubusercontent.com/1114343/196895791-1887b4f3-92e9-4db4-b578-fe1780de07f3.png">

**Comment by Kaspik** [comment]
I was looking into this today and I think this is not a problem with SequelAce itself, because they query is handed over to MySQL C++ framework, but with the setup of the procedure. If I understand it correctly, it's trying to iterate over databases/tables that it found, but it's returning the result set if found, which means it returns result once it finds (in this case, table one).

I was looking for similar issues like [this](https://stackoverflow.com/questions/34729229/mysql-stored-procedure-only-returning-one-select-query) one and interesting idea came up there: `To avoid returning the result from that query as a resultset from the procedure, you can assign the value returned by that into procedure variable or a user-defined variable.`

Could you maybe play with that / try that? I really don't know what else we could do here, MySQL is simply returning result, the result came from first table, and even based on your screenshot from MySQL console it seems like just the console returns 3 times, which of course our GUI can't do right now, so it processes the first result only.

**Comment by christatedavies** [comment]
I could possibly try this. Thanks for looking into it. It's not a huge issue, especially now I am aware of the issue. I simply run the function in the console, so I'm afraid it will be pushed to the back of my "todo list" - so feel free to close this issue. If its a limitation of the MySQL C++ framework, not a lot you can do about it.

Thanks, for the reply and research anyway. Chris
