### ISSUE TITLE
Make column type visibility optional in content view and query editor

### ISSUE THREAD

**Issue by nexbridge** [Sequel-Ace/Sequel-Ace#1614]
- Sequel Ace Version: 4.0.2 (build 20041)
- Sequel Ace Source: App Store
- macOS Version: 12.6.1
- Processor Type: Intel

Regarding https://github.com/Sequel-Ace/Sequel-Ace/issues/1559, please make this optional in Preferences -> Tables for those who don't want it - thanks!

**Comment by Jason-Morcos** [comment]
You're welcome to make a PR to add this customization option! :)

**Comment by nexbridge** [comment]
If I knew how I would, but unfortunately I'm not an Objective-C developer!  I'm hoping that this would be a straightforward change for those who know how - things like this ought to be optional really.  Thank you once again for all of the great work that you (plural) do - as a long-time Sequel Pro user and lamenter of its demise it's great to see what you've done with it.  I am a fan!

**Comment by Jason-Morcos** [comment]
Thank you!
We're trying to keep from having a preference for every single thing. The confer is three-fold:
1. We don't want to slow down new features by having to add a ton of settings every time
2. If a feature is useful 90+% of the time, we don't want to optimize for/do a lot of extra work for that last 10%
3. Having a ton of preferences isn't necessarily useful. Hundreds of options gets really crazy and makes customizing the app overwhelming to non-super-users.

In this case, I do think a preference would be nice. But I voted the ship the feature without one because I didn't think it was a huge deal either way and didn't want to hold up the feature with extra preferences work.

**Comment by nexbridge** [comment]
Yes in this case it's quite a visual change that can clutter the UI if you have a lot of columns, but I accept that it's a judgement call, although I think there's a strong argument in favour of more customisation options in general, as one size never fits all - Firefox do a good job in that regard in their about:config section. :)

**Comment by outie** [comment]
I second this request. After the last update all my windows won't show everything without scrolling horizontally because of the extra column widths. I tried resizing the header to hide the types but a refresh reset all my widths again. 

I work with the content view a lot and I can't get to all my columns without constantly scrolling horizontally now. Please let users hide the types if possible. Thank you.

**Comment by samuelbradshaw** [comment]
If you hover over a field header you get a tooltip that shows you the data type and length. This meets the same need as showing the content type directly, and is less invasive. That said, it's not as discoverable, so I can understand how some users might like to see the data type next to the field name. But I like the idea of a setting for this (I would have it turned off).

<img width="213" alt="Screen Shot 2022-11-16 at 6 49 59 PM" src="https://user-images.githubusercontent.com/7323052/202334271-c2e4cd14-0c42-4a57-bea3-c6322c5e44c9.png">

**Comment by arlomedia** [comment]
I'm looking forward to the new preference that is being added. I find these labels to be distracting and they make it harder to scan the column names.

**Comment by ethangates** [comment]
I know commenting here achieves little as I can't open a PR and fix it myself, sorry folks - but I wanted to agree with the above, it's not necessary for my workflow to see the datatypes and I can hover over the column names if I need to, I'd love to be able to toggle this off.

**Comment by Jason-Morcos** [comment]
Please try the latest beta - the fix for this issue is included in the latest 4.0.5+ beta!

https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by nexbridge** [comment]
@Jason-Morcos If you're in Content view and then you toggle the column type on/off in the Preferences, the text size of the column headers changes?

**Comment by Jason-Morcos** [comment]
> @Jason-Morcos If you're in Content view and then you toggle the column type on/off in the Preferences, the text size of the column headers changes?

Not sure, you're welcome to file a new issue. Definitely wasn't impacted by the changes in 4.0.5
