### ISSUE TITLE
Microsoft Windows 8/10/11 Support

### ISSUE THREAD

**Issue by vipinnegi90** [Sequel-Ace/Sequel-Ace#1656]
As much as I love this application to use on my macOS over any other application in this segment due to its simplicity, user-friendly features and simple look & feel, It would be great to use this application on Microsoft windows. 

I've been using Workbench or HeidiSQL for a while but, ever since I found this app and have been using it, I want to experience the same while working on my windows machine. I believe this would make great a application for Windows and would be quite popular.

Btw, I've tried to find active development or discussion on a similar topic. I couldn't find any, hence opening an FR. If there are any active ones, please point me there, I'd be glad to close this one. 

My strong suit is Flutter and I'd love to contribute to its development for Windows, Linux etc. IMO Flutter would be a great option to expand on many other platforms with a single codebase.

**Comment by samuelbradshaw** [comment]
Most database apps I've used don't feel native to macOS (look and feel). Sequel Ace is an exception. This is one of the reasons I really like Sequel Ace, and I'm afraid the native look and feel would be lost if it were switched to Flutter or another cross-platform framework. I'm not against porting Sequel Ace to other platforms, but I've never had a really good experience with a cross-platform app on Mac.

**Comment by stychos** [comment]
IMO, the application is built for macOS and around macOS, making it cross-platform will mean rebuilding it almost from scratch, which needs enormous human-hours and that, actually, will be another app.

**Comment by Kaspik** [comment]
I can say, with really sad face, this won't happen ever. If we will be able to put time on this, we might be able to bring it "cross-platform" with support for iPadOS (don't think iOS) because it shares to codebase, language and platform-API (recently) - but even that is years from now on with current number of devs behind this project.

Windows would have to start from scratch, and I don't think we have any Windows devs here. Bringing existing 10+years old codebase to Flutter is suicide unfortunately.
