### ISSUE TITLE
Command-Backtick Does Not Cycle Between Query Windows

### ISSUE THREAD

**Issue by robbpriestley** [Sequel-Ace/Sequel-Ace#1666]
- Sequel Ace Version (including build number): 4.0.4 20044
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: Ventura 13.1
- Processor Type (Intel/Apple): Apple
- MySQL Version: N/A
- macOS Localization:  

**Description**
Command-Backtick Does Not Cycle Between Query Windows. At least, not consistently. Sometimes it does, sporadically, unreliably.

**Steps To Reproduce**
1. Open multiple query windows at once
2. Press Command-Backtick to cycle between the windows

**Expected Behaviour**
Every time Command-Backtick occurs, the next open query window should come to the foreground.

**Comment by samuelbradshaw** [comment]
I have seen this as well.

**Comment by wolfswinkel** [comment]
Having the same issue. What I did found out is:
- when I have 2 tabs in a window opened and 1 connected to a server (local or external) and the other still in the connection screen
- the tab with connection screen is active
- then I can cycle through all the windows

But when I make a connected tab active and start cycling again that window won't appear anymore unless I select the tab from the windows menu. When I select the "connection list"-tab and start cycling again it will work again.

macOS Ventura 13.0.1
Sequel Ace 4.0.4 Build 20044

**Comment by wolfswinkel** [comment]
Crosspost from this thread:
https://github.com/Sequel-Ace/Sequel-Ace/issues/1618#issuecomment-1403339429

Found "the problem" and temporary "solution":
The problem is in the "first tab" of a window. When I have 3 windows with each 3 tabs open and tab1 is "the first" tab that was available. Even if I move tab1 to the place of tab3 and start shuffling through the windows it doesn't come back.
Now when I close the tab that was the first tab of the window, and then add another so I get back 3 tabs it always works when cmd+tabbing, no matter what tab you have active, connected or not. It keeps coming up.

So my workaround now is when I open a new window, I open a second tab, close the first one and then the problem is gone. Probably untill I reopen the app completely.

**Comment by robbpriestley** [comment]
An additional annoyance is that the program seems to "save up" a Command-Backtick keypress.

1. Have two windows open and connected
2. Press Command-Backtick in the first window. Nothing happens.
3. Switch to the second window using the Window menu
4. Execute a query in the second window using Command-R
5. The program executes the query in the second window but also jumps unexpectedly to the first window.

**Comment by Kaspik** [comment]
Can someone try to explain me what Query window is?

- if we are talking about tabs, then there is a system shortcut Control-Tab / Control-Shift-Tab
- if we are talking about app windows, the same shortcut the system one for switching windows should work too, but honestly - it doesn't work for me even in Safari or other apps, so not sure what's changed there.

**Comment by wolfswinkel** [comment]
@Kaspik I made a video with my phone because Quicktime screenrecording prohibited the fault (as if a fullscreen overlay does something so the problem won't occur).
https://mijndonaties.nl/query.mov
The first 9s of the video I try to let the screen go out of focus. As you can see it doesn't happen all the time. 
The next 9s I start to select some other tabs and shuffle through the diffrent windows to come back to the window with orange labels.
After 18s I start shuffling between DB's again, just to force a query, and then at 26s in the video I select a DB and the window with red labelled tabs does appear. Meaning the window with orange tabs disappeared to the background.

Hope this helps in any way :)

**Comment by Kaspik** [comment]
I think you are talking about different issue (https://github.com/Sequel-Ace/Sequel-Ace/issues/1618).

**Comment by whitslar** [comment]
@Kaspik Not sure if this is a proper fix as I don't do much Mac development, but this was driving me crazy so I poked around a bit. If I enable "Visible At Launch" in MainWindow.xib my Command+` window cycling starts behaving correctly. I'm on an M1 (Ventura 13.2.1) for reference.

**Comment by Kaspik** [comment]
Feel free to create a PR with just that change so we can merge it and other's try as well.
