### ISSUE TITLE
Can't update from 4.0.8 to 4.0.9 via Homebrew or via program on Sonoma 14.0 (M1 Macbook Pro)

### ISSUE THREAD

**Issue by dennisfransen** [Sequel-Ace/Sequel-Ace#1851]
- Sequel Ace Version: 4.0.8,20051
- Sequel Ace Source Homebrew: [Homebrew link](https://formulae.brew.sh/cask/sequel-ace#default)
- macOS Version: Sonoma 14.0
- Processor Type Apple: M1
- MySQL Version: 5.6
- macOS Localization:

**Description**
I can't update to 4.0.9 via Sequal Ace itself. And when i want to update via Homebrew. The latest version is 4.0.8. I also checked on [homebrew sequel ace](https://formulae.brew.sh/cask/sequel-ace#default) to see if i for some reason couldn't see the latest version on my machine.

**Steps To Reproduce**
1. Open Sequel Ace.
2. Press Sequel ace dropdown menu in the top left corner of the mac screen
3. Press: Check for updates
4. Press download when dialog appears
5. [.... starts downloading]
6. Dialog window dissapears after 70% download
7. Nothing more happens

**Expected Behaviour**
Check for updates and press download should update the program from 4.0.8 to 4.0.9

I tried to restart the program
I tried to uninstall it via Homebrew and installing it again
After i reinstalled Sequel Ace i tried to update again via the program itself, same issue.

**Comment by Jason-Morcos** [comment]
Homebrew installation isn't officially supported (see the Readme). We don't offer support for the Cask being out of date because we don't control it. https://github.com/Sequel-Ace/Sequel-Ace?tab=readme-ov-file#homebrew

I bet you have an installation from Homebrew which doesn't like the in-app updater because of permissions issues. I suggest our preferred install method of the macOS App Store, or directly installing from GitHub releases if you'd like to use the in-app updater.
