### ISSUE TITLE
Crashes when trying to set only a space as default value

### ISSUE THREAD

**Issue by LtMost** [Sequel-Ace/Sequel-Ace#1853]
- Sequel Ace Version (including build number): 4.0.8
- Sequel Ace Source (App Store/GitHub/Homebrew): GitHub
- macOS Version: 13.5.2
- Processor Type (Intel/Apple): Apple
- MySQL Version: 5.5.5-10.6.12-MariaDB-0ubuntu0.22.04.1
- macOS Localization: en

**Description**
trying to set the default value of a field to just a space crashes SA instantly

**Steps To Reproduce**
1. create database
2. create field |name|VARCHAR for example|255|0|0|0|0 or 1| | |None|UTF-8 Unicode (utf8mb4)|utf8mb4_unicode_ci|
3. edit the Default value and just put one space in there
4. exit edit / save / press enter
5. crash

**Expected Behaviour**
instant crash

**Related Issues**
havent found them

**Additional Context**
[crashlog.zip](https://github.com/Sequel-Ace/Sequel-Ace/files/12748438/crashlog.zip)

**Comment by Jason-Morcos** [comment]
Gotta ask - why are you trying to set a default value to a space? 🤦 😆 
Sounds like a bug indeed - but seems pretty low priority. Would be happy to review a PR if someone wants to take a stab at fixing it!

**Comment by luis-** [comment]
Looks like we are trimming the whitespace from the entered value so crash happens when default is only whitespace characters. Not user friendly that SA crashes but as a quick work around you can wrap your default value in quote since it looks like SA has some code in place to handle the quotes. I can create a PR with fix when I get a chance sometime after work.
