### ISSUE TITLE
Filters Got Reset After Export

### ISSUE THREAD

**Issue by rawkon** [Sequel-Ace/Sequel-Ace#1896]
- Sequel Ace Version (including build number): Unrelated
- Sequel Ace Source (App Store/GitHub/Homebrew): Unrelated
- macOS Version: Unrelated
- Processor Type (Intel/Apple): Unrelated
- MySQL Version: Unrelated
- macOS Localization: Unrelated

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
No.

**Description**
Filters Got Reset After Export

**Steps To Reproduce**
1. Export as SQL
2. Filters Gone!

**Expected Behaviour**
I LIKE FILTERS!

**Related Issues**

**Additional Context**

**Comment by Jason-Morcos** [comment]
Hi,

Please submit a complete issue report in order for us to investigate. That includes version numbers and a detailed description of what occurred/what you expected to occur. We require all fields in our template completed, and enough clarity to be able to understand the issue at hand. Due to the high volume of submissions we receive, incomplete issue reports will be closed.

Thank you
