### ISSUE TITLE
TCP/IP connections fail after upgrading to macOS 14.1.2

### ISSUE THREAD

**Issue by crontab** [Sequel-Ace/Sequel-Ace#1929]
- Sequel Ace Version: 4.0.13 (20062)
- Sequel Ace Source: App Store
- macOS Version: Sonoma 14.1.2
- Processor Type: Apple
- MySQL Version: 8.0.35
- macOS Localization: English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
The latest github release is the same - 4.0.13 (20062)

**Description**
Ever since I upgraded my OS to 14.1.2 all my "favorite" connections have stopped working. I'm getting this message immediately after trying to connect:

> Connection failed!
> Unable to connect to host localhost, or the request timed out.
> Be sure that the address is correct and that you have the necessary privileges, or try increasing the connection timeout (currently 10 seconds).
> MySQL said: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)

The connenction method is TCP/IP to localhost so a reference to the socket file here is irrelevant. Also, the error message is shown immediately so it's not a timeout issue.

I tried using the local socket (which in my case is `/opt/local/var/run/mysql8/mysqld.sock`), doesn't work either, in fact it never worked with Sequel Ace due to sandbox limitations. Adding the socket folder to the list of accessible files in settings doesn't help either.

Command line `mysql -h localhost` with the same db/username/password works fine.

Most frustrating thing is Sequel Ace has been working for me for years and now suddenly it doesn't after an OS upgrade. No other changes to the Sequel Ace or MySQL config were made in between.

One additional observation: Sequel Ace is not listed in the system settings dialog for file permissions for some reason.

**Comment by Jason-Morcos** [comment]
I'd check Sequel Ace's settings! Double check the SSH config and known hosts file you have selected there
You should be able to manually add Sequel Ace to the System Setting's full disk access if you'd like, but that's not required generally for normal use.

Additionally, you could try specifying 127.0.0.1 instead of localhost and seeing if that makes a difference.

**Comment by crontab** [comment]
Hi Jason,

> I'd check Sequel Ace's settings! Double check the SSH config and known hosts file you have selected there

I don't understand very well what this means. I am connecting via TCP/IP to localhost (SSL is not used). This has worked perfectly before, plus I know it should work because it does from the command line with the MySQL client, i.e. `mysql -h localhost` with the same db/user/pw.

> You should be able to manually add Sequel Ace to the System Setting's full disk access if you'd like, but that's not required generally for normal use.

I did but it didn't help, I'm getting the same error messages.

> 
> Additionally, you could try specifying 127.0.0.1 instead of localhost and seeing if that makes a difference.

Tried this too, no luck, although the error message is now different. Actually this is quite strange and it might give us a clue of what's going on.

With 127.0.0.1 the error message is 'Can't connect to MySQL server on '127.0.0.1' (61)'

With `localhost` the error message is 'Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)' even though I didn't specify this socket file anywhere in the config. Does Sequel Ace assume `localhost` means a local socket? This is very strange as it shouldn't.

I checked my `/etc/hosts` file, it hasn't changed after the OS upgrade and contains the `localhost` entry that resolves to 127.0.0.1. Plus again, this config worked before the OS upgrade.

Any ideas where else to look?

**Comment by Jason-Morcos** [comment]
The network tab in Sequel Ace's settings is where you'll want to double check that things look correct.

<img width="334" alt="Screenshot 2023-12-07 at 08 36 55" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/10710367/d5b259f4-6dd8-4525-800e-2bd3ca1be761">
<img width="812" alt="Screenshot 2023-12-07 at 08 37 20" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/10710367/99914cea-d263-4c30-b46d-e93bf4e9e1ff">


Additionally, just because it works in the command line doesn't mean it will work in Sequel Ace - Sequel Ace can't access your system SSH config (unless you select it in the network tab), and can't access many system resources/random files that SSH directly can. That being said, I understand that you were able to connect before so that makes me think maybe some config got corrupted or somehow changed, but that it's not an inherent issue with your connection setup.

**Comment by crontab** [comment]
@Jason-Morcos I added my `.ssh/known_hosts` explicitly but that didn't help unfortunately. Quick question: why does Sequel Ace need known_hosts if my TCP/IP (or local socket) connections are unencrypted?

**Comment by Jason-Morcos** [comment]
known_hosts has nothing to do with encryption - known_hosts is about hostname validation which is more basic than SSL encryption, as I understand it at least. 

I wonder if the issue in your case is something to do with the Keychain. I suggest potentially deleting a favorite connection, opening the Keychain application and searching for "Sequel" and clearing out any entires, and then re-creating the favorite connection. My hunch is perhaps your keychain was corrupted. I'm unable to reproduce this issue with the latest update

**Comment by crontab** [comment]
@Jason-Morcos nope, didn't help. I deleted the Sequel Ace entries in my KeyChain, also deleted the plist file under `~Library/Preferences`, then deleted the favorites (where are they kept btw?), created a new favorite - same result.

I might find the time to build Sequel Ace and try to debug it but before I do, could this maybe give a clue on what's going on? - The error message I'm getting mentions `/tmp/mysql.sock` even though I'm connecting via TCP/IP to `localhost`. This is obviously wrong and might be an indication of some bug, don't you think?

**Comment by Jason-Morcos** [comment]
I don't think it's related to socket stuff. We made a change about a year ago regarding local host for tcp/ip but haven't made any changes there since. IIRC it tries a non-socket connection before falling back on that. Besides, I would think putting in 127.0.0.1 would work regardless of socket issues.
Definitely am very curious what's going on here! Something funky for sure.

**Comment by crontab** [comment]
Found it! Nothing to do with Sequel Ace, it was the MySQL server config that was modified by some update process (`skip-networking`). I feel so stupid for not checking this in the first place. Sorry and thanks a lot for helping @Jason-Morcos !

**Comment by Jason-Morcos** [comment]
No worries! Glad to hear you figured it out!
