### ISSUE TITLE
Preference setting to keep the app running when last window closes

### ISSUE THREAD

**Issue by cschoenfeld** [Sequel-Ace/Sequel-Ace#2016]
As of the latest release, version 4.0.17, the app automatically quits when the last window closes. (Even if the "Prompt for confirmation before quitting" preference is checked, it ignores that preference.)

I would prefer that the app only quits when I issue the "Quit" command--which _was_ its behavior until recently. I imagine there are other users who would share that preference. 

I suggest that "Quit automatically when last window closes" should be a preference setting, instead of an unchangeable default behavior.

**Comment by Kaspik** [comment]
It was this behavior until the last release but it was a bug and memory leak. We not only kept the app running, but there was more artifacts causing sometimes connection open to DB, hangs etc., which is now fixed.

Most of the apps that behave like this usually are single-windowed, and when you click it, the same window appears again.

We are multi-tab and multi-window app and honestly it's not that easy to implement, so I would say this is a P-Never for me. 🤷🏻‍♂️

**Comment by MacGritsch** [comment]
The new behaviour is not Mac-like, feels totally strange is horrible inconvenient.
If I close a DB-Window and want to open another one, the application quits. Thats not normal and feels like the app crashed.

**Comment by eelkeblok** [comment]
Came here to say the same. Although I can imagine the position of the developer(s?), it is disappointing that all issues surrounding this are closed. As said before, it is not Mac-like to close an app when the last Window closes. It happens regularly I only have a single window open, which is connecting to the DB container of my current project, that I since restarted, so the connection is no longer valid. I guess I'll have to remember to open a new window before closing the old one, or I need to restart the app.

**Comment by lostminds** [comment]
I'm also constantly tripped up by this. Since Sequel Ace can keep multiple windows open for different connections I expect it to behave like other document style applications with multiple window support. So when I want to switch to working with another database I instinctively close the window I'm done working in and try to make a new one, only to realize Sequel Ace has then quit. Having to create a new one, then switch over to the old one to close that afterwards feels backwards and is hard to get used to.
 
Even if I understand the developers don't see this as an issue, it's obviously a big annoyance for many users considering how often bug reports or feature proposals have been added for this so I really hope they'll consider adding an option for this .

I also noticed that this quitting on closing the last open window does not trigger the "Prompt before quitting" confirmation dialogue even if you have that setting enabled.
