### ISSUE TITLE
App quits when closing last window

### ISSUE THREAD

**Issue by MacGritsch** [Sequel-Ace/Sequel-Ace#2020]
As reading in bug #2016, it is not planned to change this misbehaviour.
But please at least make it so that it quits only when last window is closed and app is disactivated.
So that I can open a new connection when last one is closed.
Only quit the app when last window is closed and user changes to another application.
Please take TextEdit (from Apple) as an example.

**Comment by Kaspik** [comment]
I thikn there is no reason for another thread especially since you replied in #2016 .

**Comment by MacGritsch** [comment]
I saw that the other one was closed.
So is it reopened to fix the issue and change it to mac-like behaviour like TextEdit?

**Comment by Kaspik** [comment]
There is nothing like mac-like or non-mac-like behavior - even native Apple apps behave both ways. Messages behave like we do, TextEdit behaves like you want. Most of the other non-native apps behave like that only if they are single windowed. Right now there is no plan or capacity to change the behavior (just being honest) to re-implement all that logic because there is just tooo much old legacy code involved... Happy to do it with some help and moving the project forward, but it's just not in our capacity. 😶

**Comment by MacGritsch** [comment]
It is simply wrong behaviour in a multiwindowed application that it directly quits when you close the last window and the application does not lose focus. In that case you can always open a new window in that application using Command+N.
See numbers.app, pages.app and also messages.app (that you noted).

**Comment by kinglozzer** [comment]
Just dropping in to say I agree this behaviour is strange. _Very few_ MacOS apps behave this way, and in fact no other multi-window apps I use behave like this, only single-window ones do.

Looks like this was introduced by https://github.com/Sequel-Ace/Sequel-Ace/pull/2001 as a workaround for a memory leak, was that bug common? I don’t recall it happening to me, but maybe I just never hit the right conditions for it.

I appreciate you probably have more important issues, but I just thought I’d add my voice to this. Thanks for your work :smile:

**Comment by MacGritsch** [comment]
I would still prefer memory-leaks vs this annoying behaviour...

**Comment by Kaspik** [comment]
I don't understand what's so different in launching the app that opens the window vs opening the window - the app launches in about ~1s which is basically instant.

Saying memory leak is preferable is ... silly, to say at least.

If we get into that anytime soon, we will of course improve this, but right now it's not a priority, that's it.

**Comment by kinglozzer** [comment]
@Kaspik the main difference for me personally, is that if I want to switch from one of my “Favourite” servers to another (e.g. from staging to production), I used to do it quickly like this:

- <kbd>CMD</kbd> + <kbd>W</kbd>
- <kbd>CMD</kbd> + <kbd>N</kbd>
- Select the new server

Now I have to consciously remember to open the new connection _before_ closing the old one, which is a bit unintuitive. Either that or I have to re-open the app via Spotlight.

> If we get into that anytime soon, we will of course improve this, but right now it's not a priority, that's it.

Understood, it's not a huge issue for me, just a minor hiccup 😃

**Comment by MacGritsch** [comment]
Same here.
When working with many Databases its a mess.
If you close one DB before you open the next, the Apple+N command is executed in the last active application or the finder -> which results in new pages, new documents, new folders etc.

**Comment by tombajzek** [comment]
I find this behavior to be **very** disconcerting. I've been using Sequel Ace and Sequel Pro before that for nearly 20 years, and this sudden change in behavior is hard to get used to. I've taken to opening a connection window and hiding it at once, never to use it, just to get around this. I hope this suggestion is helpful to others who share my frustration.

**Comment by ernstki** [comment]
I'm also eager to see the previous behavior restored. Would that I could make it happen with code, rather than just complain about it, but alas my skills lie elsewhere.

Introducing a coworker to Sequel Ace this week, also a long-time Mac user, we were _both_ confused by this, suspecting a new _macOS_ "feature" rather than a change to Sequel Ace itself.

Love it or hate it, the previous behavior was in line with expectations for multi-window Mac applications since long before Mac OS X was even a thing. I don't expect <kbd>⌘ W</kbd> to quit an app, for example.

**Comment by kinglozzer** [comment]
I think the biggest clue that this behaviour is wrong is that you get a confirmation window for `⌘ Q` but not for `⌘ W`, when both cause the app to quit 😅

I can understand not wanting to re-introduce a memory leak, but without doing so then I don’t think this will _ever_ be fixed. As mentioned in https://github.com/Sequel-Ace/Sequel-Ace/pull/2036#issuecomment-2343839974, I believe the memory leak is caused by the crash reporting functionality. I haven’t looked at it any further as I’m not an app developer, if anyone in this thread is then I’d encourage them to take a look and see if we can fix both problems at once 😄

**Comment by Kaspik** [comment]
I agree with all of you that the behavior was better, but right now I'm not open to revert it and make it as it was.

The original problem needs to be fixed, and imho it's not the crash reporting, it's the duplicated connection (https://github.com/Sequel-Ace/Sequel-Ace/issues/2115) or something related to that. I'll be happy to revert the behavior once the leak(s) is fixed and this won't be necessary.
