### ISSUE TITLE
Error when adding a new line from content view

### ISSUE THREAD

**Issue by niuliGMBH** [Sequel-Ace/Sequel-Ace#2079]
- Sequel Ace Version (including build number): 4.1.1
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 14.6.1
- Processor Type (Intel/Apple): Apple M1
- MySQL Version: 11.2.2-MariaDB
- macOS Localization: German

**Description**
When adding a new row in the content view, a default value in the field list is throwing an error. In this case the field is defined as an ENUM with a default value set to 'no'.

**Steps To Reproduce**
1. Create a new table with field test1 of type int and a second field test2 of type enum (e.g. 'no,'yes'; should not be nullable and default value set to 'no'). 
2. Try to add a new row letting test2 empty.
3. Error: Unkown column 'no' in 'field list'

<img width="287" alt="error message" src="https://github.com/user-attachments/assets/94bd0cda-03bd-49c8-8c9b-10029224ff91">

**Expected Behaviour**
New line should be savable without setting the field test2 as it was with version 4.1.0.

**Comment by jdwuzhere** [comment]
Since 4.1.1 Sequel Ace doesn't enclose default table values in quotes

CREATE TABLE `blog` (
  `id` mediumint unsigned NOT NULL AUTO_INCREMENT,
  `author` varchar(17) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT 'jd',
  `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `body` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `added` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `lang` char(2) CHARACTER SET ascii NOT NULL DEFAULT 'ru',
  `public` tinyint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `lang_` (`lang`)
) ENGINE=InnoDB AUTO_INCREMENT=257 DEFAULT CHARSET=utf8mb3;

When inserting a new row into a table, Sequel Ace executes the following statement:

INSERT INTO `blog` (`id`, `author`, `title`, `body`, `added`, `lang`, `public`) VALUES (NULL, jd, '111', '111', CURRENT_TIMESTAMP, ru, NULL);

instead of 

INSERT INTO `blog` (`id`, `author`, `title`, `body`, `added`, `lang`, `public`) VALUES (NULL, 'jd', '111', '111', CURRENT_TIMESTAMP, 'ru', NULL);

**Comment by Jason-Morcos** [comment]
Likely a regression caused by https://github.com/Sequel-Ace/Sequel-Ace/pull/2063

@vuon9 mind taking a look at this one?

**Comment by paolomartini** [comment]
This bug is still present in Build 20071

**Comment by Jason-Morcos** [comment]
Correct, we haven't released a new build yet with the fix included. This will be included in the next release.
