### ISSUE TITLE
Fails to launch under macOS 10.14.6 when built with Xcode 16

### ISSUE THREAD

**Issue by NoHalfBits** [Sequel-Ace/Sequel-Ace#2105]
- Sequel Ace Version: 4.1.3 (20074)
- Sequel Ace Source: GitHub
- macOS Version: 10.14.6

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

(no beta currently available)

**Description**

Fails to launch under macOS 10.14.6

From the crash report: 

> Termination Reason:    DYLD, [0x1] Library missing
> 
> Dyld Error Message:
>   Library not loaded: /System/Library/Frameworks/QuickLookUI.framework/Versions/A/QuickLookUI
>   Referenced from: /Applications/Sequel Ace.app/Contents/MacOS/Sequel Ace
>   Reason: image not found

Looks like the QuickLookUI framework [requires macOS 12+](https://developer.apple.com/documentation/QuickLookUI).

Sequel Ace 4.1.2. launches fine.

**Steps To Reproduce**
1. Open Sequel Ace 4.1.3 under macOS 10.14.6
2. there is no step two

**Additional Context**

[Sequel Ace 4.1.3 QuickLookUI.crash.zip](https://github.com/user-attachments/files/17187518/Sequel.Ace.4.1.3.QuickLookUI.crash.zip)

**Comment by yezigl** [comment]
same issue

Process:               Sequel Ace [12031]
Path:                  /Applications/Sequel Ace.app/Contents/MacOS/Sequel Ace
Identifier:            com.sequel-ace.sequel-ace
Version:               4.1.3 (20074)
App Item ID:           1518036000
App External ID:       869224591
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Sequel Ace [12031]
User ID:               501

Date/Time:             2024-09-30 23:23:51.262 +0800
OS Version:            Mac OS X 10.14.6 (18G9323)
Report Version:        12
Anonymous UUID:        206DD421-F6C4-4764-D3A4-293E59534D7C

Sleep/Wake UUID:       532BE2BE-D94A-4709-9D33-D808C30467AF

Time Awake Since Boot: 66000 seconds
Time Since Wake:       24000 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /System/Library/Frameworks/QuickLookUI.framework/Versions/A/QuickLookUI
  Referenced from: /Applications/Sequel Ace.app/Contents/MacOS/Sequel Ace
  Reason: image not found

Binary Images:
       0x10d73b000 -        0x10dba6fff +com.sequel-ace.sequel-ace (4.1.3 - 20074) <6A2CD639-6CAA-3C8D-A271-8D68354EAF74> /Applications/Sequel Ace.app/Contents/MacOS/Sequel Ace
       0x10dcf6000 -        0x10dd05fff +com.sequel-ace.net.wafflesoftware.ShortcutRecorder.framework.Leopard (20074) <D23CE4CB-9BDB-3B83-A4FD-E69ABF6DFD92> /Applications/Sequel Ace.app/Contents/Frameworks/ShortcutRecorder.framework/Versions/A/ShortcutRecorder
       0x10dd18000 -        0x10dd1cfff +com.sequel-ace.querykit (4.1.3 - 20074) <7607F0FA-AFBD-3A5B-9499-2BD8248D2BE9> /Applications/Sequel Ace.app/Contents/Frameworks/QueryKit.framework/Versions/A/QueryKit
       0x10dd27000 -        0x10e11dffb +com.sequel-ace.spmysql (4.1.3 - 20074) <9DE8B142-671E-313D-92B2-5A1CEC6CCFD9> /Applications/Sequel Ace.app/Contents/Frameworks/SPMySQL.framework/Versions/A/SPMySQL
       0x11adae000 -        0x11ae1870f  dyld (655.1.1) <4842B61A-B868-3146-9CA9-5582C4198B25> /usr/lib/dyld
    0x7fff399bf000 -     0x7fff3a774ff3  com.apple.AppKit (6.9 - 1671.60.112) <4AFB032C-2786-3AD7-8EDA-576956992A9C> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff3b27b000 -     0x7fff3b61dfff  com.apple.CFNetwork (978.6 - 978.6) <F6AC3859-B6F9-3212-A357-54AA096DAA9E> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff3bb34000 -     0x7fff3bb34fff  com.apple.Cocoa (6.11 - 23) <4D068A12-9E8F-3264-88BA-8426A9849AE3> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff3bed0000 -     0x7fff3c255fef  com.apple.CoreData (120 - 866.6) <132CB39B-8D58-30FA-B8AD-49BFFF34B293> /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
    0x7fff3c347000 -     0x7fff3c78dfff  com.apple.CoreFoundation (6.9 - 1575.405) <04F56DFB-C410-31B8-8AE9-7D2024DB6E22> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff3c78f000 -     0x7fff3ce1ffe7  com.apple.CoreGraphics (2.0 - 1265.13) <C4238967-56E7-3AE5-A3F4-1A878EB5FFD8> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff3d59f000 -     0x7fff3d59ffff  com.apple.CoreServices (947.2 - 947.2) <7BD142C3-402B-3294-BE74-9DD4623827E4> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff3e5cf000 -     0x7fff3e97dffb  com.apple.Foundation (6.9 - 1575.405) <9FA71865-7713-3F53-91E7-5DCEBCF4F83D> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff3ec88000 -     0x7fff3ed17fff  com.apple.framework.IOKit (2.0.2 - 1483.260.5) <C00462C2-9CF3-3E3E-BD1E-B57AF6AB562E> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff46e12000 -     0x7fff46e12fff  com.apple.quartzframework (1.5 - 23) <8C952BCD-52A8-3FD6-A000-2F3B106069D2> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff478a2000 -     0x7fff47ba3ff7  com.apple.security (7.0 - 58286.270.14) <E4396E05-1649-31B2-80D9-228C15941670> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff47fff000 -     0x7fff4806cfff  com.apple.SystemConfiguration (1.17 - 1.17) <5AD859DE-F55C-37F2-BF58-29F6234BD06C> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff4aa87000 -     0x7fff4afd7ff7  com.apple.WebKit (14607 - 14607.3.9) <7949E652-FCCA-3161-87C1-AB3C3FD0718A> /System/Library/Frameworks/WebKit.framework/Versions/A/WebKit
    0x7fff64664000 -     0x7fff64665ffb  libSystem.B.dylib (1252.250.1) <B2E16B83-D383-330A-8BD3-39526248EDFD> /usr/lib/libSystem.B.dylib
    0x7fff6489b000 -     0x7fff648a8fff  libbz2.1.0.dylib (38.200.3) <272953A1-8D36-329B-BDDB-E887B347710F> /usr/lib/libbz2.1.0.dylib
    0x7fff648a9000 -     0x7fff648fcff7  libc++.1.dylib (400.9.4) <9A60A190-6C34-339F-BB3D-AACE942009A4> /usr/lib/libc++.1.dylib
    0x7fff6535a000 -     0x7fff655bbffb  libicucore.A.dylib (62141.0.1) <A0D63918-76E9-3C1B-B255-46F4C1DA7FE8> /usr/lib/libicucore.A.dylib
    0x7fff65e9e000 -     0x7fff66623fdf  libobjc.A.dylib (756.2) <7C312627-43CB-3234-9324-4DEA92D59F50> /usr/lib/libobjc.A.dylib
    0x7fff667f5000 -     0x7fff669d2fff  libsqlite3.dylib (274.26) <6404BA3B-BCA4-301F-B2FE-8776105A2AA3> /usr/lib/libsqlite3.dylib
    0x7fff66d0e000 -     0x7fff66d20ff7  libz.1.dylib (70.200.4) <B048FC1F-058F-3A08-A1FE-81D5308CB3E6> /usr/lib/libz.1.dylib

Model: MacBookPro11,5, BootROM 427.140.8.0.0, 4 processors, Intel Core i7, 2.5 GHz, 16 GB, SMC 2.30f2
Graphics: kHW_AMDRadeonR9M370XItem, AMD Radeon R9 M370X, spdisplays_pcie_device, 2 GB
Graphics: kHW_IntelIrisProItem, Intel Iris Pro, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x152), Broadcom BCM43xx 1.0 (7.77.61.3 AirPortDriverBrcmNIC-1305.12)
Bluetooth: Version 6.0.14d13, 3 services, 27 devices, 1 incoming serial ports
Network Service: iPhone, Ethernet, en4
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512G, 500.28 GB
USB Device: USB 3.0 Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Bluetooth USB Host Controller
USB Device: iPhone
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1

**Comment by Jason-Morcos** [comment]
Looks like an Apple bug - known issue 🤦 
https://forums.developer.apple.com/forums/thread/763710

**Comment by Jason-Morcos** [comment]
@Sequel-Ace/all Anyone have an idea for how to get Xcode to stop linking QuickLookUI? Definitely seems like an Xcode 16 issue
Impacted BBT too it looks like - https://community.folivora.ai/t/bettertouchtool-will-not-launch/38688/3

**Comment by Kaspik** [comment]
@Jason-Morcos  Why do we release from Xcode 16 already? Sworch back to Xcode -5 on Xcode cloud - we are not yet ready for it. :)

**Comment by Jason-Morcos** [comment]
I think we just generally default to the latest current release - but good point! I manually set Xcode Cloud to Xcode 15.4 / macOS Sonoma 14.5, so the next build we release should be compatible with older versions of macOS again

**Comment by Jason-Morcos** [comment]
New release candidate coming out tonight (4.1.4) - please give it a try and let us know if it's fixed now!

https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by iamtoddperkins** [comment]
I received the same error this morning trying to open Sequel Ace. The pre-release fixed the issue, for me at least.
