### ISSUE TITLE
Context menu only offers "delete ALL ROWS" when there's only one row

### ISSUE THREAD

**Issue by Stokestack** [Sequel-Ace/Sequel-Ace#2143]
- Sequel Ace Version (including build number):
Version 4.1.6
Build 20078

- Sequel Ace Source (App Store/GitHub/Homebrew):
Github

- macOS Version: 15.1.1
- Processor Type (Intel/Apple): Apple
- MySQL Version: MariaDB 11.6.2
- macOS Localization: English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**
If you're viewing table contents and you right-click on a row when there are multiple rows, you can only delete one of them.
If you repeat this when only one row exists, you're nonsensically offered the ability to delete all rows.

It appears that a logical condition is backward here. The "all rows" option should be offered when there's more than one. It should also be offered when no rows are selected. Currently you can't do anything in that instance.

**Steps To Reproduce**
1. Navigate to a table that has a few rows in it, and view its contents.
2. Select a row, right-click it, and view the options.
3. Delete all rows but one.
4. Select a row, right-click it, and view the options.

**Expected Behaviour**
The option to delete all rows should be offered at all times... except perhaps for the one time it's currently offered: when there's only one row, and it's already selected.

**Related Issues**

**Additional Context**
Screen shot attached.
![nonsensicalDeleteRows](https://github.com/user-attachments/assets/68818553-641e-4472-a8b9-4aeba67d9f39)

**Comment by Jason-Morcos** [comment]
Not a bug - delete the only visible row and delete all rows are not the same thing

Delete all rows === truncate the table. 
The popup is asking you when you're deleting the only visible row if you want to run a delete where id=x or a truncate on the table.

**Comment by Stokestack** [comment]
I didn't say they were the same thing. I'm saying that it makes no sense to deny the "delete all rows" option until you've selected all rows manually.

**Comment by Jason-Morcos** [comment]
Feel dangerous to over prompt delete all rows...

**Comment by Stokestack** [comment]
But it's silly to offer it when the user has already selected all rows and is being presented with a delete option anyway. It looks like the logic is reversed in the application; that's all.

**Comment by Jason-Morcos** [comment]
The thought is if you're deleting all the rows visible, you might be selecting a subset of the total rows (due to page limits of other filters) but might be _intending_ to purge the table. That's why you get those extra two optons about resetting auto-inc and doing a delete all rows. Basically if you're trying to clear the displayed rows, we ask if you're really trying to fully clear the backing _table_.
Sure, we could present this option to delete all rows when deleting just a single row, but then we're presenting a very risky destructive action (if the user mis-clicks) when the user was likely intending to delete only one row. I feel pretty good about the way it works today :)

**Comment by Stokestack** [comment]
Thanks for the replies!
