### ISSUE TITLE
Issues with password protected SSH keys

### ISSUE THREAD

**Issue by categoryshell** [Sequel-Ace/Sequel-Ace#291]
With Sequel Pro, i could add my SSH keys to my session via the terminal and SP would use the session
to authenticate myself with those SSH keys.
The reason i add my SSH keys to my session is that they're password protected and i don't want to enter that password everytime i use that key, that day.

Unfortunately, Sequel Ace ignores this session and asks me for the password every time, which gets quite tedious.
So i said Sequel Ace can store that password in Keychain. After that, Sequel Ace is unable to find/use my key anymore and the SSH connection is out the window.
I need to manually remove that password from Keychain to get it asking for my password again.

Please make Ace working the same as Pro did, and read my SSH session.
Honestly, all my applications do that so i know it's not impossible.

I'm on OSX 10.15.4 and Sequel Ace 2.1.5 build 2073

**Comment by Jason-Morcos** [comment]
Unfortunately, Sequel Ace is a sandboxed app - we simply cannot share your session like Sequel Pro used to. It sounds like the core issue here is that there is something wrong with the store-password-to-key-in-keychain system if I understand correctly?

**Comment by categoryshell** [comment]
Then why did you sanbox it? Because it’ a App Store requirement? The place where tools like this don’t belong?

IntelliJ can do it. iTerm2 can do it. You should to it too. This kinda renders the tool useless and makes me keep using the good ol’ Sequel Pro until there is an alternative :) 

App Store is evil, and good for Candy Crush. Not dev apps like this :)

**Comment by Jason-Morcos** [comment]
I'm gonna go ahead and reopen this issue until someone in the @Sequel-Ace/all is able to verify whether or not there may be an issue with remembering ssh key passwords in the keychain so that other users don't encounter this issue!

**Comment by matzeso** [comment]
@categoryshell  
You are not really helping here. You could decide to help move this project forward, answer the questions about the keychain issues for example, but you decide to disencourage people that use their spare time to develop for the community. 
You should really try to be more thankful to contributors.

There are people out there that prefer a sandboxed app, especially in companies, because it provides way more security. 
Especially in open source projects, it is then easier to introduce security backdoors. 
With a sandboxed app, it would be way harder to introduce a backdoor.

**Comment by wrmoon** [comment]
Is this related to #285 I wonder?

**Comment by Kaspik** [comment]
There has been a lot of changes to SSH and keychain as well as bookmarks - I'm gonna close this now with 3.1.0 released. :)
