### ISSUE TITLE
SSH tunneling not working with MariaDB 10.5

### ISSUE THREAD

**Issue by warrenmelnick** [Sequel-Ace/Sequel-Ace#326]
Sequel-Ace version 2.1.6
MacOS Catalina (10.15.6)
Device: Newest MacBook Pro 16 Retina.

Ever since I upgraded my machines from MariaDB 10.1 and 10.3 to 10.5, ssh tunneling no longer works.  The SSH tunnel itself is fine, but I can no longer connect to any databases, whether local or on remote machines (local or remote to the ssh'd to machine).

The connection to the one machine which is on my local network running MariaDB 10.5 works fine, so I believe the problem is confined to ssh tunnel connections.

**Comment by Jason-Morcos** [comment]
When "it doesn't work", what's in the "Show Details" log? Could you copy and paste that to here (sanitizing out any private info)?

**Comment by warrenmelnick** [comment]
![ace](https://user-images.githubusercontent.com/6431509/91636534-66c65f00-e9cf-11ea-854f-f149051920c6.png)
<img width="557" alt="bash" src="https://user-images.githubusercontent.com/6431509/91636538-6a59e600-e9cf-11ea-86cf-a01e164ed943.png">
Attached find 2 images, one with Sequel Ace failing, the second with me doing the same thing manually (ssh in and mysql client to the server).  I do not get an option to show details, perhaps because it is not the ssh tunnel that is failing but rather the mysql connection after the ssh tunnel.

**Comment by Jason-Morcos** [comment]
@Sequel-Ace/all Have we seen this error before? I'm not sure why this would start happening with a Maria update.

**Comment by Kaspik** [comment]
Please try 3.1.0 released today.

**Comment by dalikimail** [comment]
Still really buggy application compared to Sequel Pro
Issues:
1) Can't establish two ssh connections to the same server (Sequel Pro perfectly does it)
2) After closing connection tab ssh connection is still alive. Sequel Pro have the same issue, but this doesn't inflict any real problem because you can establish new connection with Sequel Pro (you will have two ssh connections in `ps aux | grep ssh`). With Sequel Ace you can't do this because of the first problem, and you should manually kill ssh connection
3) If several connection tabs opened and there are some sql in Query, after closing left tab content of Query tab will move from right to left (as if you didn't closed left tab). Really annoying. I don't remember if such issue was in Sequel Pro (to be honest, there is terrible crashing of Pro when tab is closed, so I can't check it)
4) Moreover, after closing left tab you can't tell which tab is for which connection because something really weird starts to happen -- tab headers are good but database list and table list are from wrong tabs. It becomes completely impossible to work after closing tab, so, there are still no progress comparing with Sequel Pro

These are the most annoying bugs. Project is really good but there are a lot work to do. I hope that hotfixes will be published as soon as possible

**Comment by jamesstout** [comment]
> is really good but there are a lot work to do. I hope that hotfixes will be published as soon as possible

PRs welcome mate.

**Comment by Jason-Morcos** [comment]
@warrenmelnick Can you try the latest beta of Sequel Ace and let us know if this is still an issue?

https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by Shotz5** [comment]
Still experiencing this same issue today, updated to 4.0.16 on Sonoma 14.3.1, still encountering this bug, not sure why it was abandoned but we're encountering this after updating from MariaDB 10.4 to 10.5
