### ISSUE TITLE
Auto closing tabs issue

### ISSUE THREAD

**Issue by lipatovroman** [Sequel-Ace/Sequel-Ace#568]
Hello!
When I press on red close button - Sequel Pro closing all tabs without any notifications.
Some applications on Mac just hide window when Close button pressed.
Some application closes - but they displays notification about tabs.
I think we need new options in settings:

Behavior for close button:
-- Close application and tabs
-- Hide application window (Use long press CMD+Q to exit)
-- Close application and restore all tabs in next application start.

**Comment by Kaspik** [comment]
First of all - "Sequel Pro"? Are you talking about Sequel Pro or Sequel Ace?

As some apps (like Chrome) do require long CMD+Q command, and red close button doesn't entirely close them - afaik this is not allowed. And because we are Mac AppStore app, we should follow rules and keep behavior as it is.

In version 3.0.0 we are gonna automatically save your queries that are not saved, so you will always find them in "recent queries" thus you won't loose anything, so I don't think another prompt for close is required either.

We might think about "restore" state in the future (tabs, connections, auto-connect etc) - I don't think we will get to that in near future, sorry. 😞

**Comment by lipatovroman** [comment]
Sorry, of course I mean Sequel Ace!!!!
Ok, thank you for reply.
Will wait version 3.0.0.
Best regards.
