### ISSUE TITLE
[REQ] Be able to sync two databases structure and/or data

### ISSUE THREAD

**Issue by jlubeck** [Sequel-Ace/Sequel-Ace#57]
Issue imported from Sequel Pro repo: https://github.com/sequelpro/sequelpro/issues/72

It would be nice if you could sync the structur of 2 databases or its data
similar to what navicat allows you to do

**Comment by Jason-Morcos** [comment]
This would be cool but this is a pretty large development effort for a pretty niche group so I really don't see this happening anytime soon.

**Comment by jlubeck** [comment]
Keeping the structure of 2 databases in sync between dev and prod is niche?

**Comment by Kaspik** [comment]
Let's do this: I'll add a label to this for community and who is interested in this, feel free to open a PR. Let's revisit in a while if no one gets into that to see how many people actually upvote this. Sounds good?

**Comment by jlubeck** [comment]
Thank you for re-opening. I have no idea how to code this, otherwise I would've made a PR on the original sequel pro 😅

**Comment by Jason-Morcos** [comment]
@Kaspik has the right idea. It's a big feature and we've got a ton of very common bugs to fix first so I closed this issue initially because I don't think any of us will have the time to devote sufficient effort to getting this done. But, perhaps someone from the community is interested in working on this. Or perhaps we knock out all the bugs and can turn our attention to features like this sometime in the future!

**Comment by daltonrooney** [comment]
This would be a killer feature IMO, I would use it every day and I don't think I'm alone. I don't know if you have any commercialization plans for this application, maybe the core application remains open source and free but you could enable a premium edition as well? I would gladly sponsor on Github or pay via in-app purchase for features like this and profile sync.
