### ISSUE TITLE
Bring in Issues tagged 'security' from Sequel Pro?

### ISSUE THREAD

**Issue by tflight** [Sequel-Ace/Sequel-Ace#63]
I'm curious if any progress has been made on any [security issues identified in Sequel Pro](https://github.com/sequelpro/sequelpro/issues?q=is%3Aopen+is%3Aissue+label%3ASecurity). While carrying over all issues, or even all bugs might be tedious, it would seem appropriate to bring over the various known security issues here, perhaps as a project so users know the status.

**Comment by Jason-Morcos** [comment]
I know quite a few have already been fixed. We upgraded TLS, implemented hardened runtime, and sandboxed the app. One could bring over the issues, but I think it ought to be done in a one-at-a-time verify-it-still-exists kind of approach. Adding 100 issues doesn't really make it likely they'll be fixed. Adding a few real issues makes it quite more likely they'll get done.

**Comment by tflight** [comment]
I guess that's why I was thinking of just those 9 linked to, just to double check they've been addressed.

**Comment by Kaspik** [comment]
Newest one is 17 months old, oldest is 7 years. I lean towards not moving them until someone confirms they are still issues and opens an Issue here...

**Comment by tflight** [comment]
Except again, these are potential vulnerabilities, not necessarily bugs that people will stumble on. Just thinking it would be prudent to go through those 9 and see if those known vulnerabilities have been addressed or not.

**Comment by Jason-Morcos** [comment]
@tflight And others, you are welcome to review issues from Sequel Pro and create them as issues for Sequel Ace if they persist in the latest 2.1.0 beta! We'd be happy to review security issues. But just copying all security issues from sequel pro to sequel ace really doesn't help anyone.

**Comment by gboudreau** [comment]
- https://github.com/sequelpro/sequelpro/issues/2454: Is not a problem.
- https://github.com/sequelpro/sequelpro/issues/3362: Fixed by sandbox
- https://github.com/sequelpro/sequelpro/issues/2797: Fixed when we updated libmysqlclient to 8.0.20 (might have been fixed even before that...)
- https://github.com/sequelpro/sequelpro/issues/2499: Was fixed in https://github.com/Sequel-Ace/Sequel-Ace/commit/67649f01d870037722aaee437c38a6da12c3b215; already in Sequel Ace codebase
- https://github.com/sequelpro/sequelpro/issues/2437: Was fixed in https://github.com/Sequel-Ace/Sequel-Ace/commit/030eac5e17c69e375d7724e489483db72e791b9c; already in Sequel Ace codebase
- https://github.com/sequelpro/sequelpro/issues/1387: Was fixed in https://github.com/sequelpro/sequelpro/pull/2935; which I think we could merge.
- https://github.com/sequelpro/sequelpro/issues/1972: Don't think that is a security issue, but it is a good idea. Will send a PR in a few minutes.
- https://github.com/sequelpro/sequelpro/issues/2977: Not sure I agree that is a security issue, but maybe we could still fix that.
- https://github.com/sequelpro/sequelpro/issues/1228: I kind of agree here. If for example your query history contains the creation of a user, with a password, and you share a saved session with a co-worker, you've now given him the password of a potentially sensitive MySQL account...

**Comment by Jason-Morcos** [comment]
Excellent work, @gboudreau! Let's port over the last 4 issues you mentioned and then close out this issue.
If we could port over the first two as PRs right away, that would be awesome.

I agree that sequelpro/sequelpro#2977 is not a security issue, but indeed possibly worth fixing.
And sequelpro/sequelpro#1228 should be marked Highest Priority

**Comment by gboudreau** [comment]
PR #71 sent; I'll work on sending a new PR for sequelpro/sequelpro#1387.

**Comment by Jason-Morcos** [comment]
Created issues for the two other lingering issues. @gboudreau I'm gonna close this issue out, since you're working on PR for sequelpro/sequelpro#1387!
