### ISSUE TITLE
Certain basic queries won't run

### ISSUE THREAD

**Issue by adsussman** [Sequel-Ace/Sequel-Ace#665]
- Sequel Ace Version 3.0.1 (build 3008)
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.1
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.6.40
- macOS Localization: US(English)

**Description**
I updated to the latest store app today.  Certain basic, saved queries that I use on a daily basis are not running.  When I click to "Run Previous" (the default button), I get a "knock" sound but no response from the app (no error messages, no status change on the query, etc.).  If I change the drop down to "Run All", it works and runs the query.  On other windows, I get the same lack of response/action when it is set to Run All and only works if I change it to be Run Previous.  I cannot find a pattern as to which windows are one way versus the other.

**Comment by Kaspik** [comment]
The `knock` means there is no previous query to run. And the button doesn't say `run current` because none is selected. If you remove for example `;` at the end of the query, then add it back - the query will be grayed (background) and the button will say `run current` and it will work correctly.

The problem is specifically with the `current query` highlight and tokenization, which is mentioned already here: https://github.com/Sequel-Ace/Sequel-Ace/issues/640
