### ISSUE TITLE
Cannot connect with an empty password

### ISSUE THREAD

**Issue by klaustopher** [Sequel-Ace/Sequel-Ace#674]
- Sequel Ace Version (including build number): 3.0.1 (3008)
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.1
- Processor Type (Intel/Apple): Apple
- MySQL Version: 8.0.22 (Homebrew)
- macOS Localization: German

**Description**
My local MySQL instance on my dev machine is configured to allow `root` access without a password. When I enter this data into Sequel Ace, and try the connect button, it shows me an error that it cannot authenticate, but it tries to use a password.

![Bildschirmfoto 2020-12-22 um 15 57 47](https://user-images.githubusercontent.com/522537/102901924-80078580-446e-11eb-9022-df34a9e49f0a.png)

Error message that is shown:

![Bildschirmfoto 2020-12-22 um 15 55 51](https://user-images.githubusercontent.com/522537/102901780-4f275080-446e-11eb-88cc-1ffe97971989.png)

```
Unable to connect to host 127.0.0.1 because access was denied.

Double-check your username and password and ensure that access from your current location is permitted.

MySQL said: Access denied for user 'root'@'localhost' (using password: YES)
Access denied for user 'root'@'localhost' (using password: YES)
```

Also, the password field seems to be filled with some filler data afterwards:

![Bildschirmfoto 2020-12-22 um 15 57 57](https://user-images.githubusercontent.com/522537/102901931-81d14900-446e-11eb-9a6a-3f9400b4700d.png)

**Steps To Reproduce**
1. Enter an IP address and a username, leave password blank
2. Click on Connect
3. See that it is trying to use a password (`(using password: YES)`), eventhough the password field is empty

**Expected Behaviour**
When no password is entered, I expect the client to not use a password when connecting to the database, just like the CLI would do:

```
$ mysql -uroot
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 339
Server version: 8.0.22 Homebrew

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> exit
Bye
```

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
3.0.1 (3008) is the latest release

**Related Issues**
It seems that lately there was some trouble with the password entering and sending #604, #598, #606

**Comment by mfehr94** [comment]
Strange I am using 3.0.1 (3008) too and can't reproduce this issue.

**Comment by klaustopher** [comment]
I looked through the code for a bit and saw a lot of mentions of the macOS Keychain ... As it turns out ... I had a password stored in the Keychain (no idea how it ended up there). Deleting this fixed the issue, and I can log in.

But still, clearing the password field should yield in no password being sent to the DB for authentication, even if something is stored in the Keychain.

**Comment by andrewminion-luminfire** [comment]
I’m having similar issues on the same 3.0.1 (3008) version.

Context: our corporate policy is to avoid storing sensitive DB credentials in macOS Keychain due to some security issues it’s had in the past.

Steps to reproduce:

0. Have an existing connection from a prior version of Sequel Ace containing all connection parameters except the password.
1. Paste in the password from my password manager and attempt to connect
2. See the error message that it failed to connect due to no password
3. With the password field filled, press the “Test Connection” button and see it pass
4. Attempt to connect again and see it fail
5. Save the connection and try again
6. See it succeed

Here’s a video showing the behavior: https://www.berrycast.com/conversations/dd0136d4-15bd-5fb6-8ba3-b9f056b1dc81

I also noticed that once the password has been saved, deleting it does **not** result in failed connections as I would expect.

Here’s a video: https://www.berrycast.com/conversations/49ab3b46-7efd-581c-abfd-1192f246d365

---

This is happening with AWS RDS using the MariaDB engine (10.1.34) as well as my local DB using MariaDB 10.4.13.

I suspect the database server is not the issue…it feels like an issue with saved vs. temporary credentials in the Sequel Ace UI.

**Comment by andrewminion-luminfire** [comment]
Looks like #631 and #632 address this already.

**Comment by Kaspik** [comment]
It's not bug, it's expected behavior. If you are editing saved thing, you need to SAVE it again. Test connections works, but connection itself can't work because you didn't save it.

All your screenshots have `Save changes` enabled, which means you have existing connection edited without saving it. For quick connect, there is a quick connect option.

**Comment by Kaspik** [comment]
Re: Andrew and policy to not store the password - we would need to think about this use-case. Introducing prefill or `don't save password` option for favorites could be the case. I'll think about this use-case more for 3.0.2 after Christmas.

**Comment by andrewminion-luminfire** [comment]
> It's not bug, it's expected behavior. If you are editing saved thing, you need to SAVE it again. Test connection works, but connection itself can't work because you didn't save it.

I know this is your project so it’s completely your perogative, but what you’re saying is expected behavior is unintuitive to me as a user. If test connection works with modified credentials (compared to what is saved), connect should work just the same, and the fact that test connection and connect behave differently with credentials modified in the UI is quite confusing.

On further reflection, I guess it makes sense in the context of entering credentials, testing them, and then saving the favorite once the connection is set up successfully. In my typical use, it makes sense that whatever is filled in the UI fields would be used when connecting, rather than discarding what may be modified in the UI and instead using what’s saved.

---

Another common use case (in my experience) is to set up and save a connection with SSH and db host parameters and occasionally change the user credentials to quickly test access for another mysql user.

I understand quick connect is available as an option for one-off connections, but in some cases, it’s far faster to slightly modify an existing connection and connect than to fill in all the credentials from scratch in a quick connection.

I guess you could say this use case is starting with a saved favorite to “prefill” a quick connection, if that makes sense.

---

Thank you so much for picking this up and continuing development after Sequel Pro was abandoned. I use Sequel Ace many times daily and love it.

Hope you have a great holiday season!

**Comment by Kaspik** [comment]
It's not "my" project for sure, I'm totally open to any changes! :)

> On further reflection, I guess it makes sense in the context of entering credentials, testing them, and then saving the favorite once the connection is set up successfully. In my typical use, it makes sense that whatever is filled in the UI fields would be used when connecting, rather than discarding what may be modified in the UI and instead using what’s saved.

That's exactly where this opens question what is the correct behavior. If you have favorite query, you edit it, and hit "connect":
- should it override the saved connection?
- should it just connect and not override anything?
That's why we decided to require `save` before using the prefilled data. We can probably disable the `connect` button itself until you hit `Save`, but that might be confusing too?

> Another common use case (in my experience) is to set up and save a connection with SSH and db host parameters and occasionally change the user credentials to quickly test access for another mysql user.
> I understand quick connect is available as an option for one-off connections, but in some cases, it’s far faster to slightly modify an existing connection and connect than to fill in all the credentials from scratch in a quick connection.

I guess right click on the favorite to `duplicate` where you change things and use it might be the faster solution? Again, it's about what we should do with the edits in the moment when you connect-

> I guess you could say this use case is starting with a saved favorite to “prefill” a quick connection, if that makes sense.

If we come up with some kind of prefill, this would be solved too.

> Thank you so much for picking this up and continuing development after Sequel Pro was abandoned. I use Sequel Ace many times daily and love it.

Happy to hear that, we will try our best to keep the bar up and growing!

> Hope you have a great holiday season!

You too, be safe and take some time off!

**Comment by klaustopher** [comment]
@Kaspik I checked what you said, and I opened up a clean version of Sequel Ace, deleted all my stored connections and used quick connect:

- Entered `127.0.0.1` as the Host
- Entered `root` as the user 
- Immediately clicked the *Test Connection* button, without ever entering the password field

Sequel Ace is *still* trying to connect to the server with a password:

![Bildschirmfoto 2020-12-22 um 18 29 32](https://user-images.githubusercontent.com/522537/102916471-e6e36980-4483-11eb-8fdc-071470a55a51.png)

![Bildschirmfoto 2020-12-22 um 18 29 47](https://user-images.githubusercontent.com/522537/102916474-e8ad2d00-4483-11eb-9dea-39c8972654f5.png)

This time I made sure, that there is no password stored in the Keychain:

![Bildschirmfoto 2020-12-22 um 18 31 51](https://user-images.githubusercontent.com/522537/102916534-04b0ce80-4484-11eb-8d4c-a8477934647f.png)

---

@andrewminion-luminfire I would appreciate it, if you would not highjack this issue with an adjacent, but not equal problem. Thank you.

**Comment by Kaspik** [comment]
Interesting, I'm not able to repro that either. `Using password` for me is FALSE (correctly, as it's empty), and the if condition seems pretty straightforward too. I can't think of any reason why writing "something" and then removing it back to empty field would change the behavior.

<img width="865" alt="Screenshot 2020-12-22 at 18 43 19" src="https://user-images.githubusercontent.com/7204168/102917529-b00e5300-4485-11eb-8464-2ab2d2d67b47.png">

**Comment by klaustopher** [comment]
I just noticed this as well, when I start Sequel Ace and it is on the quick connect menu item, there seems to be a password in the field:

![Bildschirmfoto 2020-12-22 um 18 45 04](https://user-images.githubusercontent.com/522537/102917611-d207d580-4485-11eb-9e61-71975ae22f62.png)

I have no idea, where that can be coming from ... Keychain is empty for everything related to anything

**Comment by andrewminion-luminfire** [comment]
@klaustopher 

> @andrewminion-luminfire I would appreciate it, if you would not highjack this issue with an adjacent, but not equal problem. Thank you.

Sorry…based on `clearing the password field should yield in no password being sent to the DB for authentication, even if something is stored in the Keychain`, it sounded like it was caused by the same change affecting the behavior changes I had noticed, so figured some more context/perspective might be helpful in tracking it down.

**Comment by j03k64** [comment]
I had a similar issue and it wasn't until I actually closed the app and reopened it after saving changes would it connect.  I entered in the info (over ssh connection), clicked save changes, then test connection.  And it then cleared my password and said it couldn't connect.  The main difference for me was in the error modal, it said "(using password: NO)".  Even though I entered the password and saved changes. I entered the password again, clicked save changes followed by test connection and it failed again.

I entered the password one last time, saved changes, restarted the application and clicked on connect and then it worked.

**Comment by klaustopher** [comment]
Checking out current `main` build

**Comment by klaustopher** [comment]
Error is still happening for me 🤪 with the current `main` branch...

I added a breapoint in the connection method and saw that there is a password:

![Bildschirmfoto 2020-12-23 um 10 03 36](https://user-images.githubusercontent.com/522537/102979324-34a0b600-4506-11eb-810a-c969f5d8c2cd.png)

I have no idea, where this is coming from, I will spend a few more minutes finding out where it is coming from

**Comment by klaustopher** [comment]
Looking at those lines in a debugger:

https://github.com/Sequel-Ace/Sequel-Ace/blob/2bf774dbe9038b20d7e41cb0fe0f21c355c4d49a/Source/Controllers/MainViewControllers/ConnectionView/SPConnectionController.m#L922-L925

Both `connectionKeychainItemName` and `connectionKeychainItemAccount` are `nil`.

**Comment by Kaspik** [comment]
Those lines are just prefilling data when you change selection in favorites.

So to summarize:
- you open the app and select Quick Connect
- you enter 127.0.0.1, root, and leave the rest blank
- you hit connect - and it doesn't connect and shows warning "using password: yes"

is that right?

**Comment by klaustopher** [comment]
Correct.

And the password is coming from Keychain. I have tracked down the item and it seems to have something to do with my iCloud Account. The name of the Keychain item is my AppleID, and the programs that are accessing it are:

![Bildschirmfoto 2020-12-23 um 10 19 42](https://user-images.githubusercontent.com/522537/102980818-63b82700-4508-11eb-92a5-44fc1d85d59d.png)

I looked through my passwords, and this is not a password I am using anywhere ... This is all super super confusing

**Comment by Kaspik** [comment]
Yeah I have a branch with modern keychain handling, the current one was implemented for OS X 10.9 years and years ago...

I have no idea how quick connect could be using a password, because favorite name is nil, it can't get it from anywhere.

**Comment by klaustopher** [comment]
I just deleted the Password from Keychain, and now when starting the App (regardless if XCode version or App Store version) it is asking for Keychain Access for another object:

![Bildschirmfoto 2020-12-23 um 10 21 45](https://user-images.githubusercontent.com/522537/102981090-cdd0cc00-4508-11eb-9525-0859ff1bad75.png)

I think requesting data from the Keychain with `name = nil` and `account = nil` requests something unintended and if you just allow access to it, this password will be used. I think if `connectionKeychainItemName` and `connectionKeychainItemAccount` should be

- either prefixed with something Sequel Ace specific or
- a request to the keychain should not be made if either of those is `nil`

---

My problem is now fixed, by not giving SequelAce **any** access to Keychain items, but I don't think this is a proper way for everybody

**Comment by klaustopher** [comment]
> I have no idea how quick connect could be using a password, because favorite name is nil, it can't get it from anywhere.

Well, I added a breakpoint at 
https://github.com/Sequel-Ace/Sequel-Ace/blob/2bf774dbe9038b20d7e41cb0fe0f21c355c4d49a/Source/Controllers/MainViewControllers/ConnectionView/SPConnectionController.m#L922

and it got called *immediately* when starting the app

**Comment by Kaspik** [comment]
Because you have any favorite in left sidebar, right? So on app start, it selects it.

But it's a good point about keychainName being nil shouldn§t be prompting for anything, looking into it even beffore the Keychain rewrite.

**Comment by klaustopher** [comment]
Nope, it is completely empty

**Comment by klaustopher** [comment]
I guess (only ever used the iOS keychain, never the one on the mac), a simple conditional around 
https://github.com/Sequel-Ace/Sequel-Ace/blob/2bf774dbe9038b20d7e41cb0fe0f21c355c4d49a/Source/Controllers/MainViewControllers/ConnectionView/SPConnectionController.m#L925-L931

to only access the Keychain, if `connectionKeychainItemName` and `connectionKeychainItemAccount` are not `nil` should be enough there

**Comment by Kaspik** [comment]
Multiple issues found, thank you for tracking this with me:
- prefilling data for quick connect instead of early return
- getting the password only if name and accounts are valid

I added couple more check in there just to be sure.

The weirdest thing is that this code hasn't been touched for more than 5 years. Anything...

**Comment by Kaspik** [comment]
@klaustopher Could you please try the branch? Or wait for master, up to you. :)

**Comment by klaustopher** [comment]
For the last 3 years, I have been mostly using Postgres professionally and did not have a chance to use Sequel-Pro/Ace. No I am back in a project that uses MySQL and was coming back to this tool.

I have no recollection if I also had this issue with Sequel Pro back then

**Comment by klaustopher** [comment]
`keychainImprovements` branch works for me without prompting for any keychain items. But not able to do a proper code review.

Thanks for fixing this issue!

**Comment by Kaspik** [comment]
Cool, yeah guys will do the code review, happy to hear it doesn't even prompt for random things.... wuf. Thanks for help!

**Comment by websmurf** [comment]
Not entirely sure if it's the same issue, but most likely related ⬆️

**Comment by klaustopher** [comment]
Let's hope its fixed once for all now :D Thanks for the quick work

**Comment by modestaspruckus** [comment]
Macos monterey 12.1 still cannot connect with empty password (no keychains stored)

**Comment by Jason-Morcos** [comment]
> Macos monterey 12.1 still cannot connect with empty password (no keychains stored)

The issue discussed in this thread was fixed.
Please take a look at our documentation at https://sequel-ace.com and open a new issue if you're still having issues getting connected and we can investigate. Please fully fill out the issue template when submitting.
