### ISSUE TITLE
Connection password multiple issues

### ISSUE THREAD

**Issue by jeanrajotte** [Sequel-Ace/Sequel-Ace#675]
- Sequel Ace Version (including build number): 3.0.1 build 3008
- Sequel Ace Source (App Store/GitHub/Homebrew): Apple Store and now homebrew
- macOS Version:  11.0.1 (20B29)
- Processor Type (Intel/Apple): 3.1 GHz Dual-Core Intel Core i7
- MySQL Version: 5.6.10
- macOS Localization: ?  en_CA ?

**Description**
Cannot make connections if password is not saved.

**Steps To Reproduce**

1. open connection definition (cmd-n) where password is not stored
2. input password
3. click "connect"
4. the password is erased
5. S-ACE reports connection cannot be made without password.

1. Alternatively, open connection definition where password is not stored
2. input password
3. store definition
4. click "connect"
5. connection happens

**Expected Behaviour**
Use the password as given when given and don't try to update the stored connection when clicking "connect".

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Related Issues**

Possibly, once a connection is made and I try to clone the connection into another tab (cmd-shift-t) S-ACE prompts to access the keychain (for nothing, every time). Click "deny" (twice) and the process continues and completes.

**Additional Context**

**Comment by Kaspik** [comment]
Seems like might be related to https://github.com/Sequel-Ace/Sequel-Ace/issues/674

Based on "Open connection definition" I assume you are using favorites where you are filling in the password always == editing favorite connection? If so, it might be related to https://github.com/Sequel-Ace/Sequel-Ace/issues/674#issuecomment-749652353 and not saving the favorite.

**Comment by jeanrajotte** [comment]
@Kaspik it might be related,  I can't tell from allllll the stories in there.  My workflow is that I have favorites indeed, saved without password, and I put the password in the form just in order to login and don't re-save the favorite.  This worked perfectly in ACE as well as PRO, until the latest release.
I do see the UI change between pressing "connect" and the error dialog:  The password field gets blanked out on its own, then the error says "no password".  Of course!

**Comment by Kaspik** [comment]
Yes, that changed. If you edit a favorite, you need to save it first - so clicking "connect" without saving it is trying to connect without the password itself. It was changed because the behavior is confusing - if you are editing the favorite, should connecting connect and discard changes? Should it save the changes? For this reason it changed to connect with the favorite before editing (in your case without password) or requires to save the edit thus save the password to keychain.

For your use-case the app doesn't work now. 😞 

I wonder why so many users use the app without storing the keys in keychain?

**Comment by jeanrajotte** [comment]
Thanks for the explanation. It's a breaking change IMO, something that was perfectly functional.

If I want to save a favorite in its current state in the form, I click "save".

> I wonder why so many users use the app without storing the keys in keychain?

Because the passwords are very sensitive to my employer, so I keep them in a special place and only input them JIT. Saving them in the keychain, if my machine ever gets cracked, would be less secure, IMO. I might be completely wrong about this, but it doesn't matter. Something that was not broken got broken.

No, it's not confusing.  I click a favorite because I want to populate the form w/ the majority of its data for a specific connection. I complete the data, make the connection, I'm done.

That's why there are distinct buttons: Save is not connect. Connect is not save.

**Comment by jeanrajotte** [comment]
> For your use-case the app doesn't work now. 😞

Why did you have to make this breaking change? It was soooo fine, exactly as expected, with its distinct buttons.

Why does pressing "connect" attempt to save first?  That's the breaking change. There's already a button dedicated to that function.

**Comment by jeanrajotte** [comment]
> If you edit a favorite

I believe this is a misunderstanding. I'm not "editing" a favorite.  The form where I'm adding data in order to connect is NOT a "favorite", it's the connection form.  I populated it from a favorite, but it is not a favorite. I created a favorite when I saved a form with a name.

IOW, the "favorite" is the data object that was persisted by name.  The connection form is just a form with data for the one connection I'm trying to make now.

**Comment by jeanrajotte** [comment]
p.p.p.s.  :-)

There are other programs that work exactly like what I'm describing, which is why this model has never been confusing to me, years of SequelPro later. e.g. Filezilla has the same notion - save the form for a FTP connection vs. use the form for a connection. Connect does not save.

**Comment by Kaspik** [comment]
> That's why there are distinct buttons: Save is not connect. Connect is not save.

But "Connect" is in this case also "Discard changes". The expectation from our side wasn't that people are using favorites half-filled, but as a favorite connections with password in Keychain as Keychain is completely save solution provided by system. The only way how to get to the password is to steal your computer, crack into that, then also hack into your keychain that is protected via passwords and can be remotely wiped through Apple ID.

> Why does pressing "connect" attempt to save first? That's the breaking change. There's already a button dedicated to that function.

It doesn't. Connect simply connects with the saved favorite - not with the edited form.

> Why did you have to make this breaking change? It was soooo fine, exactly as expected, with its distinct buttons.

Because it felt like it's broken and it confused users. They had favorite, changed the password after it was changed in db, hit connect, it connected, but next time it didn't work again. And it didn't work because they didn't save the change. I understand it's clear for you as you are used to it, but users that are storing the password need to remember to save the change after changing password.

> I believe this is a misunderstanding. I'm not "editing" a favorite. The form where I'm adding data in order to connect is NOT a "favorite", it's the connection form. I populated it from a favorite, but it is not a favorite. I created a favorite when I saved a form with a name.

No, you are editing a favorite. The highlighted thing in left pane (list of favorites) is your favorite. Thus you are editing the favorite.

We will need to come up with some kind of pre-fill FROM saved favorite because we want to make all users happy, but it will be after Christmas as AppStore is already closed starting tonight. :)

**Comment by jeanrajotte** [comment]
I don't understand how users "got confused". This functionality has been in place for years. There's a dedicated "save" button that appears if you change the form - isn't that clear enough?  
I understand you're trying to please everyone, I hope you don't create a monster in the process :-)

**Comment by jeanrajotte** [comment]
I just pressed cmd-n to see all this again and this appeared:

![Screen Shot 2020-12-22 at 16 56 54](https://user-images.githubusercontent.com/312996/102936780-cb259680-4476-11eb-94ca-010c2fb17d03.jpg)

It's wrong in a couple of way!  "Safari bla bla extension"  ?   And why at the beginning of the sequence?

Also, what's the point of a favorite using the keychain?  If I store the password in the keychain to use it JIT, w/o storing it in the favorite, won't the same problem happen?

I appreciate you're having this convo w/ me, it's not obvious to maintain an app for everyone and this app is great!

I'M CONFUSED.
If I save the favorite without a password, then input the password and press connect, you're saying you're saving the favorite because the form has changed?  But you're not. You blank out the changed field and fail to connect because of No password.

There's a "save changes" button , that is all that is needed.

I'll stop now.  Cheers.

**Comment by Kaspik** [comment]
> you're saying you're saving the favorite because the form has changed? But you're not.

Nono, that's not what I'm saying - I'm saying that "without hitting save, the "connect" button just tries to connect with the `unchanged` form ignoring all your changes - in your case form without password." If you would hit "save", we would store the password to keychain and use it next time / every time.

Yeah we are not sure why these Keychain prompts act like `Safari`, `Firebase` or whatever, we are looking into this. 😕

Anyways I'm just about to open a PR with quick change to allow connection with edits in form until we come up with better solution for prefill with no password.

**Comment by sebastiansulinski** [comment]
Same thing experienced this morning - I don't save passwords for security purposes so it's a bit of a bummer.
