### ISSUE TITLE
Release Appstore 3.0.1 has some bugs

### ISSUE THREAD

**Issue by sidbenac** [Sequel-Ace/Sequel-Ace#689]
Great work by the way, big fan of the new app. thank you for the awesome app. 

- 3.0.1 build 3008 appstore
- Macos Big sur on Intel

since the latest update here's the problems : 

- app closes unexpectedly when I click on a view when in content mode
- on the SQL editor, if I past a request, I only see run previous, not able to run the actual pasted request
- sometimes, unable to run a request on SQL editor, as it is not considered as previous, I need to add a space, so it triggers a change and then I can run it
- sometimes, When I run a request and then want to edit a row in the results, it is not possible it doesn't allow me to edit. I need to restart the app to make it work.
- the button run current is not present.
![image](https://user-images.githubusercontent.com/8508974/103030257-6f681580-4529-11eb-91fa-d390d60d9fab.png)

**Comment by Jason-Morcos** [comment]
Please follow the issue template in the future, it makes it easier for us to follow. Additionally, it's helpful to open one "issue" per bug, rather than combining several bugs into one big issue report. We fix bugs one at a time generally, so it's easier and more straight forward to have several smaller issues rather than 1 big issue.

> app closes unexpectedly when I click on a view when in content mode
Please open a new issue for this and follow the template. We can't debug this without knowing what version of MySQL you're using

> on the SQL editor, if I past a request, I only see run previous, not able to run the actual pasted request
I think this is related to #640. The button changes between run current/previous depending on what query it has selected and if you're after a semicolon.

> sometimes, unable to run a request on SQL editor, as it is not considered as previous, I need to add a space, so it triggers a change and then I can run it
This does duplicate #640, an already open issue about this bug

> sometimes, When I run a request and then want to edit a row in the results, it is not possible it doesn't allow me to edit. I need to restart the app to make it work.
Duplicates #671 and will be fixed in next release

> the button run current is not present
See above, The button changes between run current/previous depending on what query it has selected and if you're after a semicolon.


Please please please follow the template for new issues and really only include one bug per issue. In the future, large multi-issue reports like this will be closed without as detailed a response as it's very difficult for us to manage.
