### ISSUE TITLE
Password Always Changed

### ISSUE THREAD

**Issue by suhardiyan** [Sequel-Ace/Sequel-Ace#705]
Hi, im using sequel ace version 3.0.1 and Using Mac oS Big Sur 11.1

The problem is, whenever I input specific password, its always changed automatically, how can I fix this issue ? 

thankyou

**Comment by Jason-Morcos** [comment]
Please try the latest beta and let us know if it's fixed in the upcoming 3.0.2 release! The final 3.0.2 release will be available soon.

https://github.com/Sequel-Ace/Sequel-Ace/releases

If not fixed in the latest beta, feel free to open a new issue but follow the issue template including detailed steps to reproduce and detailed setup info.
