### ISSUE TITLE
Feature: Persist state on restart

### ISSUE THREAD

**Issue by aleemb** [Sequel-Ace/Sequel-Ace#729]
Most editors these days persist the state so on restart things are where you left them. I use the query editor liberally and the Ace client crashes every now and again. If the state were preserved and restored that would be super convenient and user friendly.

**Comment by jamesstout** [comment]
Hmmm, code in the app controler:

```objc
// Because we are a document-based app we automatically adopt window restoration on 10.7+.
// However that causes a race condition with our own window setup code.
// Remove this when we actually support restoration.
if([window respondsToSelector:@selector(setRestorable:)])
    [window setRestorable:NO];
```

Not sure how easy it is ... will investigate

**Comment by Kaspik** [comment]
We do save query editor on app close (not sure if also crash) as of 3.0.0.

We do not support restoration because app start setup is terrible. And we won't support it for some it unfortunately because that's a lot of code to rewrite...

**Comment by erikbaan** [comment]
Especially with the current amount of crashes, persisting state would be awesome.

Maybe it could be approached like this:

- Keep track of 'current state' on changes: open tabs/connections, current table filters/sorting, current query tab contents
- Add a 'restore previous session' button if a current state is available. This will just execute all the actions needed to achieve the same state. Like 'open connection', 'add filter', 'set sorting', 'open another connection', 'write query tab contents' etc.

In comparison to other DB management apps, this is what bothers me the most about SequelPro/Ace.
I usually have more than 5 connections open, with custom queries in each connection, and using the query history is not useful for restoring because the mix of the different connections. And it crashes like once in 2 days.

Keeping the same query tab contents for a connection would be a major improvement.

**Comment by aleemb** [comment]
@Kaspik How about a naive implementation like if you assigned persisted each query editor text based on the `host+db+user+incrementing_id` hash or some such.

On restart, if a user opens up a connection to the same host+db+user, you can restore the last-persisted query editor state and use `1` for `incrementing_id`. If the user opens another window, you could use `2` for `incrementing_id`. This sort of naive implementation would skip the whole app start setup and just dump the query editor contents to a file on keyup or some such and would bypass the whole app start setup.

**Comment by xiangbohua** [comment]
that was a big job

**Comment by Kaspik** [comment]
Project hierarchy and windows refactoring is now being rewritten as part of project https://github.com/Sequel-Ace/Sequel-Ace/projects/7

It might allow system restoration too.

**Comment by xiangbohua** [comment]
why the last version can't stop a running query such as a sort on a big table?

**Comment by Jason-Morcos** [comment]
> why the last version can't stop a running query such as a sort on a big table?

Unrelated to this issue. Please open a new issue to report a new bug.
