### ISSUE TITLE
Time zone feature unusable

### ISSUE THREAD

**Issue by bytejedi** [Sequel-Ace/Sequel-Ace#914]
- What version of Sequel-Ace are you using?      3.2.2 (3021)
- What version of macOS are you running on?      10.14.6
- What device(s) are you using Sequel-Ace on?    Mac mini(2018)

Hi! The Timezone issues appeared on my device.  
I have tried with some other time zones and always back to the UTC.

![image](https://user-images.githubusercontent.com/43159905/109284678-15523c00-785b-11eb-9f85-c4a26fd56070.png)

_Originally posted by @bytejedi in https://github.com/Sequel-Ace/Sequel-Ace/issues/439#issuecomment-786541391_

**Comment by Jason-Morcos** [comment]
I believe the crux of the issue is still what @jamesstout noted before
https://github.com/Sequel-Ace/Sequel-Ace/issues/439#issuecomment-717721892

Is this correct? Is your mysql time_zone_names table empty/nonexistent, @bytejedi? If so, try seeding it with the proper data

The alert is new in 3.2.2. Before, we were just silently not applying the timezone. Now we let you know when we can't do so.

**Comment by bytejedi** [comment]
Thank you for your reply.

> Is this correct? Is your mysql time_zone_names table empty/nonexistent
correct, time_zone_name table is empty.

> The alert is new in 3.2.2. Before, we were just silently not applying the timezone. Now we let you know when we can't do so.
okay,I'm looking forward to,thank you for your hard work

**Comment by Kaspik** [comment]
I'm not sure what we can do here, user needs to have the entry in mysql timezone table.
